Repository kube-reporting/metering-operator, pull requests merged in 2018-12, with the labels that each got.

#523 charts,manifests,Documentation: Move metering CRs to openshift-reporting and openshift-metering charts
  Documentation/configuring-aws-billing.md
  Documentation/configuring-storage.md
  charts/openshift-metering/requirements.yaml
  charts/openshift-metering/templates/default-storage-location.yaml
  charts/openshift-metering/values.yaml
  charts/openshift-reporting/Chart.yaml
  charts/openshift-reporting/templates/datasources.yaml
  charts/openshift-reporting/templates/prom-queries/node-allocatable.yaml
  charts/openshift-reporting/templates/prom-queries/node-capacity.yaml
  charts/openshift-reporting/templates/prom-queries/pod-cpu-usage.yaml
  charts/openshift-reporting/templates/prom-queries/pod-memory-usage.yaml
  charts/openshift-reporting/templates/prom-queries/pod-persistent-volume-request.yaml
  charts/openshift-reporting/templates/report-queries/aws-billing.yaml
  charts/openshift-reporting/templates/report-queries/cluster-capacity.yaml
  charts/openshift-reporting/templates/report-queries/cluster-usage.yaml
  charts/openshift-reporting/templates/report-queries/cluster-utilization.yaml
  charts/openshift-reporting/templates/report-queries/node-cpu.yaml
  charts/openshift-reporting/templates/report-queries/node-memory.yaml
  charts/openshift-reporting/templates/report-queries/pod-cpu-aws.yaml
  charts/openshift-reporting/templates/report-queries/pod-cpu.yaml
  charts/openshift-reporting/templates/report-queries/pod-memory-aws.yaml
  charts/openshift-reporting/templates/report-queries/pod-memory.yaml
  charts/openshift-reporting/templates/report-queries/pod-volume-request.yaml
  charts/openshift-reporting/values.yaml
  charts/reporting-operator/templates/custom-resources/datasources.yaml
  charts/reporting-operator/templates/custom-resources/storage/default.yaml
  charts/reporting-operator/values.yaml
  hack/deploy-custom.sh
  manifests/metering-config/aws-billing.yaml
  manifests/metering-config/s3-storage.yaml
  manifests/metering-config/shared-storage.yaml
Labels: size/L

#524 reporting-operator: add pv phase
  charts/openshift-reporting/templates/prom-queries/persistentvolumeclaim-phase.yaml
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-phase.yaml
  charts/openshift-reporting/values.yaml
Labels: size/M

#528 pkg/operator/prestostore: Check errors writing to buffer and improve errors
  pkg/operator/prestostore/prometheusmetric.go
Labels: size/S

#529 pkg/operator: Don't add comma unless a new metric is being added to buffer
  pkg/operator/prestostore/prometheusmetric.go
Labels: size/M

#525 pkg/operators: Improve validation of scheduledReports and reports
  pkg/apis/metering/v1alpha1/util/scheduled_report_util.go
  pkg/operator/queues.go
  pkg/operator/reports.go
  pkg/operator/scheduled_reports.go
  test/e2e/scheduled_report_test.go
  test/framework/collect.go
Labels: size/L

#526 Update ScheduledReports to support Report features
  pkg/apis/metering/v1alpha1/scheduled_report.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/scheduled_reports.go
  pkg/operator/scheduled_reports_test.go
  test/e2e/main_test.go
  test/e2e/report_test.go
  test/e2e/scheduled_report_test.go
  test/framework/framework.go
  test/framework/report.go
  test/integration/main_test.go
  test/integration/report_test.go
  test/integration/scheduled_report_test.go
  test/testhelpers/assert.go
Labels: size/XL

#531 Bump version to 0.12.0-latest
  VERSION
  manifests/deploy/openshift/alm/metering.0.12.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.12.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/XL

#535 minor typo fix
  Documentation/report.md
Labels: size/XS

#538 Dockerfile.*: Pass --setopt=skip_missing_names_on_install=False to yum
  Dockerfile.e2e
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
  Dockerfile.reporting-operator
  Dockerfile.reporting-operator.rhel
Labels: size/S

#539 Makefile: Try to compile e2e/integration tests in test target
  Makefile
Labels: size/XS

#464 Documentation: Document where images are built for origin/OCP
  Documentation/dev/builds.md
  hack/ocp-util/ocp-metering-chart-values.yaml
Labels: size/L, skip-all

#540 Fix duplicate /etc/passwd entries from dynamic uid entrypoint handling
  Makefile
  charts/hdfs/templates/configmap.yaml
  charts/presto/templates/hive-scripts-configmap.yaml
  charts/presto/templates/presto-common-config.yaml
  charts/superset/templates/scripts-configmap.yaml
Labels: size/M

#501 pkg,Documentation: Support more than 1 type for ReportGenerationQuery inputs
  Documentation/reportgenerationqueries.md
  pkg/apis/metering/v1alpha1/report_generation_query.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/reporting/validate.go
Labels: size/M

#542 charts: Set global.ownerReferences to {} so chart can be rendered without helm-operator
  charts/openshift-metering/values.yaml
Labels: size/XS

#543 Fix continuous upgrade failures
  charts/metering-ci/Chart.yaml
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  hack/deploy-continuous-upgrade.sh
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/e2e-ci.sh
  hack/integration-ci.sh
Labels: size/L

#544 charts,hack: Give more CPU to hive-metastore in continuous-upgrade CI jobs
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  hack/deploy-continuous-upgrade.sh
Labels: size/S

#527 charts/presto: Configure hive server and metastore readiness/liveness probes
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/values.yaml
Labels: size/M
