Repository kube-reporting/metering-operator, pull requests merged in 2018-11, with the labels that each got.

#451 docs: update writing-custom-queries
  Documentation/writing-custom-queries.md
Labels: size/XS

#453 pkg/operator: Queue dependent Reports and ScheduledReports of ReportGenerationQueries when query is initialized
  pkg/operator/query.go
Labels: size/M

#452 manifests: Add additionalPrinterColumns to CRDs for display purposes
  manifests/custom-resource-definitions/report.crd.yaml
  manifests/custom-resource-definitions/reportdatasource.crd.yaml
  manifests/custom-resource-definitions/reportgenerationquery.crd.yaml
  manifests/custom-resource-definitions/scheduledreport.crd.yaml
Labels: size/M

#455 pkg/operator: Skip Report,ScheduledReport,ReportGenerationQuery sync if spec is unchanged
  pkg/operator/queues.go
Labels: size/M

#456 docs: writing custom query for openshift update
  Documentation/writing-custom-queries.md
Labels: size/XS

#458 Drop scheduledReport table before creating
  pkg/operator/scheduled_reports.go
Labels: size/M

#450 Cluster pvc storage request
  charts/reporting-operator/templates/custom-resources/report-queries/pod-volume-request.yaml
  test/e2e/main_test.go
Labels: size/M

#457 Combine helm-operator Dockerfile with metering-operator Dockerfile
  Dockerfile.metering-operator
  Makefile
  images/helm-operator/Dockerfile
Labels: size/M

#460 Remove hadoop image build and update chart to handle configuration and adding of scripts
  Makefile
  charts/hdfs/templates/configmap.yaml
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/namenode-statefulset.yaml
  charts/hdfs/values.yaml
  hack/deploy-custom.sh
  hack/render-metering-chart-override-values.sh
  images/hadoop/Dockerfile
  images/hadoop/check-datanode-healthy.sh
  images/hadoop/datanode-entrypoint.sh
  images/hadoop/entrypoint.sh
  images/hadoop/etc/core-site.xml
  images/hadoop/etc/hdfs-site.xml
  images/hadoop/etc/mapred-site.xml
  images/hadoop/namenode-entrypoint.sh
  manifests/metering-config/latest-versions.yaml
Labels: size/XL

#461 manifests: Add short names to long CRDs
  manifests/custom-resource-definitions/reportdatasource.crd.yaml
  manifests/custom-resource-definitions/reportgenerationquery.crd.yaml
  manifests/custom-resource-definitions/reportprometheusquery.crd.yaml
Labels: size/XS

#466 charts/reporting-operator: Lower readiness probe period
  charts/reporting-operator/values.yaml
Labels: size/XS

#463 pkg/operator: Update resource DeepCopies to happen earlier
  pkg/operator/datasources.go
  pkg/operator/prestotables.go
  pkg/operator/query.go
  pkg/operator/reports.go
  pkg/operator/scheduled_reports.go
Labels: size/M

#465 Remove hive image build, customize hive in chart
  Makefile
  charts/presto/templates/_helpers.tpl
  charts/presto/templates/hive-common-config.yaml
  charts/presto/templates/hive-configmap.yaml
  charts/presto/templates/hive-metastore-config.yaml
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-scripts-configmap.yaml
  charts/presto/templates/hive-secrets.yaml
  charts/presto/templates/hive-server-config.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/values.yaml
  hack/deploy-custom.sh
  hack/render-metering-chart-override-values.sh
  images/hive/Dockerfile
  images/hive/conf/beeline-log4j2.properties
  images/hive/conf/hive-env.sh
  images/hive/conf/hive-exec-log4j2.properties
  images/hive/conf/hive-log4j2.properties
  images/hive/conf/hive-site.xml
  images/hive/conf/ivysettings.xml
  images/hive/conf/llap-daemon-log4j2.properties
  images/hive/hive-entrypoint.sh
  images/hive/json-serde-1.3.8-jar-with-dependencies.jar
  images/hive/metastore.sh
  manifests/metering-config/latest-versions.yaml
Labels: size/XL

#468 Bump release to 0.9.0
  VERSION
  manifests/deploy/generic/alm/metering.0.9.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.9.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.package.yaml
  manifests/deploy/generic/alm/metering.subscription.yaml
  manifests/deploy/generic/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/alm/metering.0.9.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.9.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/XXL

#467 Documentation: Add new sections to release doc
  Documentation/dev/release.md
Labels: size/M, skip-all

#473 charts/reporting-operator: Make node-memory/cpu-capacity/allocatable queries filterable
  charts/reporting-operator/templates/custom-resources/report-queries/node-cpu.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/node-memory.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-cpu.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-memory.yaml
Labels: size/L

#471 Only validate non-zero imported metric count of ReportDataSources that are dependencies of queries being tested
  pkg/operator/reporting/validate.go
  test/e2e/main_test.go
  test/framework/collect.go
  test/framework/framework.go
  test/framework/reportgenerationquery.go
Labels: size/L

#454 Set ScheduledReport condition failure if validation fails
  pkg/apis/metering/v1alpha1/util/scheduled_report_util.go
  pkg/operator/query.go
  pkg/operator/scheduled_reports.go
Labels: size/M

#469 Run a single e2e/integration test per jenkins job
  hack/e2e-test-runner.sh
  jenkins/gke-e2e.groovy
  jenkins/gke-integration.groovy
  jenkins/main.groovy
  jenkins/openshift-e2e.groovy
  jenkins/openshift-integration.groovy
  jenkins/vars/testRunner.groovy
Labels: size/L

#476 pkg/operator/reporting: Fetch direct ReportDataSource dependencies
  pkg/operator/reporting/validate.go
Labels: size/S

#477 pkg/operator: Validate cron.expression is specified when using cron Schedule
  pkg/operator/scheduled_reports.go
Labels: size/XS

#478 charts/reporting-operator: Add ReportGenerationQueries on cluster-wide capacity
  charts/reporting-operator/templates/custom-resources/report-queries/cluster.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/node-cpu.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/node-memory.yaml
  test/e2e/main_test.go
Labels: size/L

#479 pkg/operator: Do not immediately import after creating ReportDataSource table
  pkg/operator/datasources.go
Labels: size/XS

#480 charts/hdfs: Add rack awareness
  charts/hdfs/templates/configmap.yaml
  charts/hdfs/values.yaml
Labels: size/M

#482 charts/reporting-operator: Add cluster usage reports
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-capacity.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-usage.yaml
  test/e2e/main_test.go
Labels: size/L

#486 Fixup local port-forward scripts
  cmd/reporting-operator/start.go
  hack/run-local-with-port-forward.sh
  pkg/operator/operator.go
Labels: size/M

#483 Add cluster utilization reports that compare usage and capacity
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-capacity.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-usage.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-utilization.yaml
  test/e2e/main_test.go
Labels: size/L

#488 charts/reporting-operator: Fix usage query double counting
  charts/reporting-operator/templates/custom-resources/prom-queries/pod-cpu-usage.yaml
  charts/reporting-operator/templates/custom-resources/prom-queries/pod-memory-usage.yaml
Labels: size/XS

#485 charts: Set JVM options for hdfs, hive and presto
  charts/hdfs/templates/configmap.yaml
  charts/presto/templates/hive-scripts-configmap.yaml
  charts/presto/templates/presto-coordinator-config.yaml
  charts/presto/templates/presto-worker-config.yaml
Labels: size/S

#484 Support setting max query length in presto and reporting-operator
  charts/openshift-metering/values.yaml
  charts/operator-metering/values.yaml
  charts/presto/templates/presto-coordinator-config.yaml
  charts/presto/templates/presto-worker-config.yaml
  charts/presto/values.yaml
  charts/reporting-operator/templates/reporting-operator-config.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/values.yaml
  cmd/reporting-operator/start.go
  pkg/operator/operator.go
  pkg/operator/prestostore/prometheusmetric.go
Labels: size/M

#489 charts/presto: Make JVM configuration more parameterized and tunable
  Documentation/install-metering.md
  charts/presto/templates/_helpers.tpl
  charts/presto/templates/presto-common-config.yaml
  charts/presto/templates/presto-coordinator-config.yaml
  charts/presto/templates/presto-coordinator-deployment.yaml
  charts/presto/templates/presto-worker-config.yaml
  charts/presto/templates/presto-worker-deployment.yaml
  charts/presto/values.yaml
Labels: size/L

#487 Improve performance when importing bulk amounts of ReportDataSource data
  charts/reporting-operator/templates/reporting-operator-config.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/values.yaml
  cmd/reporting-operator/start.go
  manifests/custom-resource-definitions/reportdatasource.crd.yaml
  pkg/apis/metering/v1alpha1/report_datasource.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
  pkg/operator/operator.go
  pkg/operator/prestostore/importer.go
  pkg/operator/promsum.go
  pkg/operator/queues.go
Labels: size/L

#490 charts/reporting-operator: Use `dt` column in cluster-capacity queries.
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-capacity.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/cluster-usage.yaml
Labels: size/S

#491 Documentation,manifests: Break apart documentation and example configurations
  Documentation/common-configuration.md
  Documentation/configuring-aws-billing.md
  Documentation/configuring-hive-metastore.md
  Documentation/configuring-storage.md
  Documentation/manual-install.md
  Documentation/metering-config.md
  Documentation/olm-install.md
  manifests/metering-config/aws-billing.yaml
  manifests/metering-config/custom-storage.yaml
  manifests/metering-config/custom-storageclass-values.yaml
  manifests/metering-config/custom-values.yaml
  manifests/metering-config/resource-limits.yaml
  manifests/metering-config/s3-storage.yaml
  manifests/metering-config/shared-storage.yaml
Labels: size/XL, skip-all

#492 Documentation,manifests: Document exposing reporting API outside of cluster
  Documentation/common-configuration.md
  Documentation/configuring-reporting-operator.md
  Documentation/metering-config.md
  manifests/metering-config/expose-route.yaml
Labels: size/L, skip-all

#493 Document difference between openshift and non-openshift installs for default Promethus URL config
  Documentation/configuring-reporting-operator.md
Labels: size/XS, skip-all

#495 Documentation: Fix broken links in new Exposing the reporting API doc
  Documentation/common-configuration.md
  Documentation/configuring-reporting-operator.md
Labels: size/S, skip-all

#497 minor update to use openssl instead of pwgen which is not included by…
  manifests/metering-config/expose-route.yaml
Labels: needs-ok-to-test, size/XS, skip-all

#494 jenkins: Update continuous upgrade job to re-use testRunner and work better for continuous-upgrades
  hack/deploy-custom.sh
  hack/deploy.sh
  jenkins/continuous-upgrade.groovy
  jenkins/deploy.groovy
  jenkins/openshift-continuous-upgrade.groovy
  jenkins/vars/testRunner.groovy
  test/e2e/main_test.go
Labels: size/L

#498 jenkins: Add back continuous upgrade job
  jenkins/continuous-upgrade.groovy
Labels: size/M, skip-all

#499 jenkins: Always set commit/PR status and fix status value on success for main job
  jenkins/main.groovy
  jenkins/vars/testRunner.groovy
Labels: size/M

#500 manifests,hack,jenkins: Deploy default set of ScheduledReports in continuous-upgrade job
  hack/deploy-continuous-upgrade.sh
  jenkins/vars/testRunner.groovy
  manifests/reports/cluster-capacity-daily.yaml
  manifests/reports/cluster-capacity-hourly.yaml
  manifests/reports/cluster-usage-daily.yaml
  manifests/reports/cluster-usage-hourly.yaml
  manifests/reports/cluster-utilization-daily.yaml
  manifests/reports/cluster-utilization-hourly.yaml
  manifests/reports/namespace-usage-daily.yaml
  manifests/reports/namespace-usage-hourly.yaml
Labels: size/L

#503 Bump VERSION to 0.10.0-latest
  VERSION
  manifests/deploy/generic/alm/metering.0.10.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.10.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.package.yaml
  manifests/deploy/generic/alm/metering.subscription.yaml
  manifests/deploy/generic/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/alm/metering.0.10.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.10.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/XXL

#504 Make it easier to run CI scripts locally
  Dockerfile.e2e
  Makefile
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/deploy.sh
  hack/e2e-ci.sh
  hack/e2e-test-runner.sh
  hack/integration-ci.sh
  hack/lib/init.sh
  hack/lib/util.sh
  hack/openshift-install.sh
  hack/openshift-uninstall.sh
  hack/run-e2e-tests.sh
  hack/run-integration-tests.sh
  manifests/deploy/reporting-operator-clusterrole.yaml
Labels: size/L

#509 pkg/operator: Hoist map creation to outer loop for creating metric labels map when converting
  pkg/operator/prestostore/importer.go
Labels: size/XS

#508 pkg/operator: Properly store health checks in subdir of storage location
  pkg/operator/operator.go
Labels: size/XS

#510 Add superset chart for interacting with Presto
  charts/openshift-metering/requirements.yaml
  charts/openshift-metering/values.yaml
  charts/operator-metering/requirements.yaml
  charts/operator-metering/values.yaml
  charts/superset/.helmignore
  charts/superset/Chart.yaml
  charts/superset/README.md
  charts/superset/templates/NOTES.txt
  charts/superset/templates/_helpers.tpl
  charts/superset/templates/datasources-configmap.yaml
  charts/superset/templates/deployment.yaml
  charts/superset/templates/env-secret.yaml
  charts/superset/templates/ingress.yaml
  charts/superset/templates/pvc.yaml
  charts/superset/templates/scripts-configmap.yaml
  charts/superset/templates/server-config-secret.yaml
  charts/superset/templates/svc.yaml
  charts/superset/values.yaml
  manifests/metering-config/superset.yaml
Labels: size/XL

#505 manifests/reports; Remove duplicate usage reports in hourly usage report file
  manifests/reports/cluster-usage-hourly.yaml
Labels: size/M

#512 Minor updates to scripts and manifests to align with dev-preview guide instructions
  hack/install.sh
  hack/openshift-install.sh
  manifests/deploy/openshift-helm-operator-values.yaml
  manifests/deploy/openshift/helm-operator/metering.yaml
Labels: size/XS

#513 Bump version for 0.11.0 release
  VERSION
  manifests/deploy/generic/alm/metering.0.11.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.package.yaml
  manifests/deploy/generic/alm/metering.subscription.yaml
  manifests/deploy/generic/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/alm/metering.0.11.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/XL

#514 charts/{hdfs,presto}: Store presto, hive, hdfs GC logs into an emptyDir
  charts/hdfs/templates/configmap.yaml
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/namenode-statefulset.yaml
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-scripts-configmap.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/templates/presto-coordinator-config.yaml
  charts/presto/templates/presto-coordinator-deployment.yaml
  charts/presto/templates/presto-worker-config.yaml
  charts/presto/templates/presto-worker-deployment.yaml
Labels: size/M

#515 Enable passing pre-existing secret with AWS credentials to hive/presto
  Documentation/configuring-storage.md
  charts/presto/templates/_helpers.tpl
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/templates/presto-aws-credentials-secret.yaml
  charts/presto/templates/presto-common-config.yaml
  charts/presto/values.yaml
  manifests/metering-config/s3-storage.yaml
Labels: size/M

#521 pkg/{hive,presto}: Improve error message for timeout while waiting for a connection
  pkg/hive/connection.go
  pkg/presto/connection.go
Labels: size/S

#522 Support setting tolerations and affinity for all pods
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/namenode-statefulset.yaml
  charts/hdfs/values.yaml
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/templates/presto-coordinator-deployment.yaml
  charts/presto/templates/presto-worker-deployment.yaml
  charts/presto/values.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/values.yaml
Labels: size/M

#519 Remove generic deploy platform
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
  Documentation/olm-install.md
  Makefile
  charts/operator-metering/.gitignore
  charts/operator-metering/.helmignore
  charts/operator-metering/Chart.yaml
  charts/operator-metering/requirements.lock
  charts/operator-metering/requirements.yaml
  charts/operator-metering/templates/_metadata.yaml
  charts/operator-metering/values.yaml
  hack/create-metering-manifests.sh
  hack/deploy-custom.sh
  hack/lib/init.sh
  manifests/deploy/generic-alm-values.yaml
  manifests/deploy/generic-helm-operator-values.yaml
  manifests/deploy/generic/alm/metering.0.10.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.10.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.11.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.7.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.7.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.7.1-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.8.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.8.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.9.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.9.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.package.yaml
  manifests/deploy/generic/alm/metering.subscription.yaml
  manifests/deploy/generic/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/generic/helm-operator/metering-operator-role.yaml
  manifests/deploy/generic/helm-operator/metering-operator-rolebinding.yaml
  manifests/deploy/generic/helm-operator/metering-operator-service-account.yaml
  manifests/deploy/generic/helm-operator/metering.yaml
Labels: size/XXL

#517 Fix AWS ReportDataSource
  charts/reporting-operator/templates/custom-resources/report-queries/aws-billing.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-cpu-aws.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-memory-aws.yaml
  pkg/operator/aws_usage_hive.go
Labels: size/S

#518 Improve ReportGenerationQuery dependency validation error handling
  pkg/operator/query.go
  pkg/operator/reporting/validate.go
Labels: size/L

#516 reporting-operator: add pvc-usage and capacity
  charts/reporting-operator/templates/custom-resources/prom-queries/persistentvolumeclaim-capacity.yaml
  charts/reporting-operator/templates/custom-resources/prom-queries/persistentvolumeclaim-usage.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/persistentvolumeclaim-capacity.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/persistentvolumeclaim-usage.yaml
  charts/reporting-operator/values.yaml
Labels: size/L
