Repository kube-reporting/metering-operator, pull requests merged in 2018-10, with the labels that each got.

#410 charts/reporting-operator: Enable configuring log level
  charts/reporting-operator/templates/reporting-operator-config.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/values.yaml
Labels: size/XS

#409 Change Promsum ReportDataSource periodic collection to use workqueues
  pkg/operator/datasources.go
  pkg/operator/operator.go
  pkg/operator/promsum.go
  pkg/operator/queues.go
Labels: size/L

#412 hack: Adjust HDFS PVC size for continuous upgrade job
  hack/deploy-continuous-upgrade.sh
  hack/deploy-custom.sh
  hack/run-local-with-port-forward.sh
Labels: size/S

#413 cmd: Use ParseFlags directly before SetFlagsFromEnv to properly get merged flags
  cmd/reporting-operator/start.go
Labels: size/XS

#411 charts,cmd: Update reporting-operator env var prefix to REPORTING_OPERATOR_
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  cmd/reporting-operator/start.go
Labels: size/M

#415 pkg/operator: Requeue AWSBilling ReportDataSources instead of relying on resync
  pkg/operator/datasources.go
Labels: size/XS

#414 Add table and full endpoint docs
  Documentation/reportgenerationqueries.md
Labels: size/S

#407 Support collecting metrics from custom Prometheus
  Documentation/reportdatasources.md
  pkg/apis/metering/v1alpha1/report_datasource.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
  pkg/operator/operator.go
  pkg/operator/promsum.go
Labels: do-not-merge/work-in-progress, size/L

#417 pkg/operator: Fix panic caused by incorrect assignment
  pkg/operator/datasources.go
Labels: size/S

#419 Doc Fix
  Documentation/reportgenerationqueries.md
Labels: size/XS

#418 images/presto: Switch to using presto base image
  images/presto/Dockerfile
  images/presto/entrypoint.sh
  images/presto/json-serde-1.3.8-jar-with-dependencies.jar
Labels: size/M

#422 Documentation: document cron scheduling
  Documentation/report.md
Labels: skip-all

#428 Merge release-0.8 and bump VERSION to 0.8.0-latest
  VERSION
  manifests/deploy/generic/alm/metering.0.8.0-latest.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.0.8.0.clusterserviceversion.yaml
  manifests/deploy/generic/alm/metering.package.yaml
  manifests/deploy/generic/alm/metering.subscription.yaml
  manifests/deploy/generic/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/alm/metering.0.8.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.8.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/XXL

#427 images/hadoop: Bump to hadoop 3.1.1
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/namenode-statefulset.yaml
  charts/hdfs/values.yaml
  charts/reporting-operator/values.yaml
  images/hadoop/Dockerfile
  images/hadoop/check-datanode-healthy.sh
  images/hadoop/datanode-entrypoint.sh
  images/hadoop/namenode-entrypoint.sh
  images/hadoop/start-name.sh
Labels: size/M

#432 images/presto: Change to root before running yum
  images/presto/Dockerfile
Labels: size/XS

#431 charts,images: Remove separate metering-presto image
  Makefile
  charts/presto/templates/_helpers.tpl
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/templates/presto-aws-credentials-secrets.yaml
  charts/presto/templates/presto-catalog-config-secret.yaml
  charts/presto/templates/presto-common-config.yaml
  charts/presto/templates/presto-coordinator-config.yaml
  charts/presto/templates/presto-coordinator-deployment.yaml
  charts/presto/templates/presto-jmx-config.yaml
  charts/presto/templates/presto-worker-config.yaml
  charts/presto/templates/presto-worker-deployment.yaml
  charts/presto/values.yaml
  hack/deploy-custom.sh
  hack/render-metering-chart-override-values.sh
  images/presto/Dockerfile
  images/presto/entrypoint.sh
  images/presto/etc/catalog/hive.properties
  images/presto/etc/catalog/jmx.properties
  images/presto/etc/config.properties
  images/presto/etc/jvm.config
  images/presto/etc/log.properties
  images/presto/etc/node.properties
  images/presto/jmx-exporter-config.yml
Labels: size/XL

#421 persistent volume and persistent volume claim prom queries
  charts/reporting-operator/templates/custom-resources/prom-queries/pod-persistent-volume-request.yaml
  charts/reporting-operator/values.yaml
Labels: do-not-merge/work-in-progress, size/S

#433 ReportGenerationQueries: less-than instead of less-than-or-equal at end of reports
  Documentation/reportgenerationqueries.md
  Documentation/writing-custom-queries.md
  charts/reporting-operator/templates/custom-resources/report-queries/node-cpu.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/node-memory.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-cpu-aws.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-cpu.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-memory-aws.yaml
  charts/reporting-operator/templates/custom-resources/report-queries/pod-memory.yaml
  test/integration/testdata/reports/namespace-cpu-request.json
  test/integration/testdata/reports/namespace-cpu-usage.json
  test/integration/testdata/reports/namespace-memory-request.json
  test/integration/testdata/reports/namespace-memory-usage.json
  test/integration/testdata/reports/node-cpu-utilization.json
  test/integration/testdata/reports/node-memory-utilization.json
  test/integration/testdata/reports/pod-cpu-request.json
  test/integration/testdata/reports/pod-cpu-usage.json
  test/integration/testdata/reports/pod-memory-request.json
  test/integration/testdata/reports/pod-memory-usage.json
Labels: size/M

#424 Documentation: roll-up report guide & explanation
  Documentation/index.md
  Documentation/report.md
  Documentation/rollup-reports.md
Labels: size/L, skip-all

#425 Documentation/report: add custom inputs info
  Documentation/report.md
Labels: size/S, skip-all

#435 Dockerfile.reporting-operator: Use /go instead of $GOPATH for copying source
  Dockerfile.reporting-operator
Labels: size/XS

#434 Adds reportgenerationquery for PVC Request
  charts/reporting-operator/templates/custom-resources/report-queries/pod-volume-request.yaml
  test/e2e/main_test.go
Labels: size/L

#440 Documentation,manifests: Update configuration docs to cover setting image versions
  Documentation/metering-config.md
  manifests/metering-config/latest-versions.yaml
Labels: size/S, skip-all

#441 Documentation: Fix template fields in filtering timestamp for writing-custom-queries guide
  Documentation/writing-custom-queries.md
Labels: size/XS, skip-all

#442 charts/presto: Add AWS credentials env vars back to hive env helper template
  charts/presto/templates/_helpers.tpl
  charts/presto/templates/hive-common-secrets.yaml
Labels: size/S

#443 pkg/operator: Handle already started reports missing their table
  pkg/operator/reports.go
Labels: size/M

#445 test/framework: Change CollectMetricsOnce to collect up to 5 minutes before current time
  test/e2e/scheduled_report_test.go
  test/framework/collect.go
Labels: size/S

#437 add namespace pvc query
  charts/reporting-operator/templates/custom-resources/report-queries/pod-volume-request.yaml
  test/e2e/main_test.go
Labels: size/M

#444 hack,Makefile: Add a script to run metering-operator locally
  Documentation/manual-install.md
  Makefile
  hack/install.sh
  hack/lib/init.sh
  hack/run-metering-operator-local.sh
Labels: size/M

#446 test: Set scheduled reportStart/end to a range which definitely was collected
  test/e2e/scheduled_report_test.go
  test/framework/report.go
Labels: size/S

#447 hack/run-metering-operator-local.sh: Run container as root to give perms to kubeconfig
  hack/run-metering-operator-local.sh
Labels: size/XS

#448 test/e2e: Check that the scheduledReport has reported on the period
  test/e2e/scheduled_report_test.go
Labels: size/S

#449 Makefile: Run tests with testcoverage and write coverage profile to a file
  .dockerignore
  .gitignore
  Makefile
Labels: size/XS, skip-e2e, skip-integration
