Repository kube-reporting/metering-operator, pull requests merged in 2019-02, with the labels that each got.

#572 charts/presto: move hive metastore timeout config into presto config
  charts/presto/templates/_helpers.tpl
  charts/presto/values.yaml
Labels: size/XS

#573 charts/presto: Support configuring hive metastore client timeout
  charts/presto/templates/hive-configmap.yaml
  charts/presto/values.yaml
Labels: size/XS

#567 hack,Documentation: Support custom metering-operator image in install scripts
  Dockerfile.e2e
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
  Documentation/dev/release.md
  Documentation/install-metering.md
  Documentation/manual-install.md
  Makefile
  hack/create-alm-manifests.sh
  hack/custom-metering-operator-install-wrapper.sh
  hack/deploy-e2e.sh
  hack/deploy.sh
  hack/e2e-test-runner.sh
  hack/extract_helm_dep_repos.py
  hack/extract_helm_dep_repos.sh
  hack/faq.repo
  hack/install.sh
  hack/jsontoyaml
  hack/lib/init.sh
  hack/uninstall.sh
  hack/yamltojson
Labels: size/L

#575 charts: Move left over prom queries from reporting-operator chart to openshift-reporting chart
  charts/openshift-reporting/templates/prom-queries/persistentvolumeclaim-capacity.yaml
  charts/openshift-reporting/templates/prom-queries/persistentvolumeclaim-usage.yaml
Labels: size/XS

#579 charts: Update resources in apps apiGroup apiVersion to v1 from v1beta1
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/namenode-statefulset.yaml
  charts/helm-operator/templates/deployment.yaml
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/templates/presto-coordinator-deployment.yaml
  charts/presto/templates/presto-worker-deployment.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/M

#584 Use origin-base:v3.11 since latest is now using the UBI which only works in origin-ci
  Dockerfile.reporting-operator
Labels: size/XS

#578 Update scripts, charts, and documentation for OLM install
  Documentation/install-metering.md
  Documentation/manual-install.md
  Documentation/olm-install.md
  charts/metering-alm/templates/clusterserviceversion.yaml
  charts/metering-alm/templates/package.yaml
  charts/metering-alm/templates/subscription.yaml
  charts/metering-olm/Chart.yaml
  charts/metering-olm/templates/catalogsourceconfig.yaml
  charts/metering-olm/templates/clusterserviceversion.yaml
  charts/metering-olm/templates/operatorgroup.yaml
  charts/metering-olm/templates/package.yaml
  charts/metering-olm/templates/subscription.yaml
  charts/metering-olm/values.yaml
  hack/alm-install.sh
  hack/alm-uninstall.sh
  hack/create-metering-manifests.sh
  hack/create-olm-manifests.sh
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/generate-metering-manifests.sh
  hack/lib/init.sh
  hack/lib/util.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  hack/render-alm-override-values.sh
  hack/render-olm-override-values.sh
  manifests/deploy/common-alm-values.yaml
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift-alm-values.yaml
  manifests/deploy/openshift-olm-values.yaml
  manifests/deploy/openshift/alm/metering.0.11.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.12.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.13.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.0.13.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/openshift/olm/metering.operatorgroup.yaml
  manifests/deploy/openshift/olm/metering.package.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
  manifests/metering-config/default.yaml
Labels: size/XXL

#585 images/helm-operator: Handle less than $RELEASE_HISTORY_LIMIT configmaps
  images/helm-operator/run-operator.sh
Labels: size/XS

#587 Prepare for using ci-operator
  Dockerfile.src
  Documentation/dev/developer-guide.md
  Makefile
  OWNERS
  jenkins/build.groovy
  jenkins/vars/testRunner.groovy
Labels: size/M

#583 Remove helm cli requirements from custom install
  Documentation/dev/release.md
  Documentation/manual-install.md
  Makefile
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/generate-metering-manifests.sh
  hack/install.sh
  hack/jq/custom-metering-operator-deployment.jq
  hack/jq/custom-metering-role.jq
  hack/jq/custom-metering-rolebinding.jq
  hack/lib/customize-manifests.sh
  hack/lib/init.sh
  hack/render-helm-operator-override-values.sh
  hack/render-metering-chart-override-values.sh
  hack/uninstall.sh
Labels: size/L

#589 Documentation: Fix typos and improve docs on report `status.conditions`
  Documentation/report.md
Labels: approved, lgtm, size/XS

#592 it's -> its and similar typos
  Documentation/ansible-install.md
  Documentation/api.md
  Documentation/configuring-reporting-operator.md
  Documentation/dev/jenkins.md
  Documentation/metering-architecture.md
  Documentation/olm-install.md
  Documentation/report.md
  Documentation/reportgenerationqueries.md
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#593 your -> you're
  Documentation/configuring-reporting-operator.md
  Documentation/dev/builds.md
  Documentation/manual-install.md
  Documentation/using-metering.md
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#595 Documentation: clarify when to override prometheusURL
  Documentation/configuring-reporting-operator.md
Labels: approved, lgtm, size/XS

#590 reporting-operator: add ability to configure CA
  charts/reporting-operator/templates/reporting-operator-config.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/values.yaml
  cmd/reporting-operator/start.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#598 hack,charts,Makefile,jenkins: Updates for origin CI to run e2e/integration
  Makefile
  charts/metering-ci/templates/metering.yaml
  hack/deploy-e2e.sh
  hack/e2e-ci.sh
  hack/e2e.sh
  hack/integration-ci.sh
  hack/integration.sh
  hack/lib/init.sh
  hack/lib/tests.sh
  jenkins/openshift-e2e.groovy
  jenkins/openshift-integration.groovy
  jenkins/vars/testRunner.groovy
Labels: approved, lgtm, size/L

#596 charts/openshift-metering: Add config option to disable creating prometheus rbac resources
  charts/openshift-metering/templates/monitoring-rbac.yaml
  charts/openshift-metering/values.yaml
Labels: approved, lgtm, size/XS

#600 reporting-operator-local: allow custom prom host
  Documentation/manual-install.md
  hack/run-local-with-port-forward.sh
Labels: approved, lgtm, size/S

#602 Makefile: Restrict `make verify` diff to specific files/directories
  Makefile
Labels: approved, lgtm, size/XS
