Repository kube-reporting/metering-operator, pull requests merged in 2019-11, with the labels that each got.

#1012 Documentation/dev: Clarify differences in app registry namespaces better
  Documentation/dev/testing-olm-ocp-install.md
Labels: approved, lgtm, size/XS

#1007 [release-4.2] bug 1766341: hack: Fix mirroring to work for digests
  hack/get-metering-package-images.sh
  hack/mirror-ose-images-into-cluster.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#1013 Dockerfile.metering-ansible-operator*: set -x before yum commands
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
Labels: approved, lgtm, size/XS

#1005 Support running the e2e suite locally.
  Makefile
  cmd/deploy-metering/main.go
  hack/e2e.sh
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/install.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/deployframework/local.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/XL

#1018 test/e2e: Rename the reporting test files to reflect their names in the test table.
  test/e2e/report_dynamic_input_data_test.go
  test/e2e/report_static_input_data_test.go
Labels: approved, lgtm, size/XS

#1011 test: Add support for testing an invalid MeteringConfig.
  cmd/deploy-metering/main.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/helpers.go
  pkg/operator/deploy/install.go
  pkg/operator/deploy/uninstall.go
  test/deployframework/context.go
  test/deployframework/helpers.go
  test/deployframework/local.go
  test/e2e/main_test.go
  test/e2e/meteringconfig_missing_storage_spec.go
  test/testhelpers/assert.go
Labels: approved, lgtm, size/L

#1019 bug 1755606: Verify that the s3 credentials secret exists.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1020 test/deployframework: Create the local operator logs without a trailing suffix.
  test/deployframework/local.go
Labels: approved, lgtm, size/XS

#1014 [release-4.2]: bug 1757551: charts/openshift-metering: Update cpu/memory usage promqueries to handle many to many matching error
  charts/openshift-metering/values.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1027 bug 1763303: Fix handling of AdditionalArtifactKeys in AWS billing report manifests
  pkg/aws/client.go
  pkg/aws/manifest.go
  pkg/operator/datasources.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1023 Merge feature-e2e-rewrite into master
  Makefile
  cmd/deploy-metering/main.go
  hack/delete-ns.sh
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/deploy.sh
  hack/e2e.sh
  hack/run-e2e-tests.sh
  hack/run-test-cleanup.sh
  hack/unit.sh
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/install.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
  test/deployframework/helpers.go
  test/deployframework/local.go
  test/e2e/main_test.go
  test/e2e/meteringconfig_missing_storage_spec.go
  test/e2e/report_dynamic_input_data_test.go
  test/e2e/report_static_input_data_test.go
  test/e2e/testdata/datasources/node-allocatable-cpu-cores.json
  test/e2e/testdata/datasources/node-allocatable-memory-bytes.json
  test/e2e/testdata/datasources/node-capacity-cpu-cores.json
  test/e2e/testdata/datasources/node-capacity-memory-bytes.json
  test/e2e/testdata/datasources/persistentvolumeclaim-capacity-bytes.json
  test/e2e/testdata/datasources/persistentvolumeclaim-phase.json
  test/e2e/testdata/datasources/persistentvolumeclaim-usage-bytes.json
  test/e2e/testdata/datasources/pod-request-cpu-cores.json
  test/e2e/testdata/datasources/pod-request-memory-bytes.json
  test/e2e/testdata/datasources/pod-usage-cpu-cores.json
  test/e2e/testdata/datasources/pod-usage-memory-bytes.json
  test/e2e/testdata/reports/namespace-cpu-request.json
  test/e2e/testdata/reports/namespace-cpu-usage.json
  test/e2e/testdata/reports/namespace-memory-request.json
  test/e2e/testdata/reports/namespace-memory-usage.json
  test/e2e/testdata/reports/namespace-persistentvolumeclaim-usage.json
  test/e2e/testdata/reports/node-cpu-utilization.json
  test/e2e/testdata/reports/node-memory-utilization.json
  test/e2e/testdata/reports/persistentvolumeclaim-capacity.json
  test/e2e/testdata/reports/persistentvolumeclaim-usage.json
  test/e2e/testdata/reports/pod-cpu-request.json
  test/e2e/testdata/reports/pod-cpu-usage.json
  test/e2e/testdata/reports/pod-memory-request.json
  test/e2e/testdata/reports/pod-memory-usage.json
  test/integration/report_test.go
  test/reportingframework/framework.go
  test/testhelpers/assert.go
  test/testhelpers/helpers.go
Labels: approved, lgtm, size/XXL

#1025 Documentation: Add the required 'managed' property to a PrestoTable example.
  Documentation/prestotables.md
Labels: size/XS

#996 Return correct resource_id for Azure
  charts/openshift-metering/templates/openshift-reporting/report-queries/node-cpu.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/node-memory.yaml
Labels: approved, lgtm, ok-to-test, size/M

#1015 K8s Event Creation Module
  images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py
Labels: approved, lgtm, size/L

#1030 images/metering-ansible-operator: Configure storage earlier in the role execution.
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, lgtm, size/XS

#1032 Makefile: Remove the integration targets.
  Makefile
Labels: approved, lgtm, size/S

#1031 hack: Remove the unused test helper scripts after merging the feature-e2e-rewrite branch.
  hack/e2e-test-runner.sh
  hack/integration.sh
Labels: approved, lgtm, size/L

#1026 images: Update the k8s_status module to better handle merging conditions.
  images/metering-ansible-operator/roles/meteringconfig/library/k8s_status.py
Labels: approved, lgtm, size/L

#1035 Documentation: Remove unused release header from the developer guide.
  Documentation/dev/developer-guide.md
Labels: size/XS

#1036 OWNERS: Remove chancez as approver and add timflannagan1
  OWNERS
Labels: approved, lgtm, size/XS

#1038 rh-verified-operators is the replacement for rh-osbs-operators which …
  Documentation/dev/testing-olm-ocp-install.md
Labels: approved, lgtm, ok-to-test, size/XS

#1021 Add ability to set Prometheus Presto connector configuration options in MeteringConfig CRD
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
Labels: approved, lgtm, size/L

#1034 images: Remove the task that prints the variables prefixed with 'meteringconfig_*'.
  images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml
Labels: approved, lgtm, size/S

#1037 cmd,pkg,test: Move the deploy package down a directory level.
  cmd/deploy-metering/main.go
  pkg/deploy/deploy.go
  pkg/deploy/helpers.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
Labels: approved, lgtm, size/XS

#1039 images: Remove the unused/empty README from the MeteringConfig role.
  images/metering-ansible-operator/roles/meteringconfig/README.md
Labels: approved, lgtm, size/M

#1033 Docker image update for k8 event module
  images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py
Labels: approved, lgtm, size/S

#1040 Update prometheus URL configuration link
  Documentation/install-metering.md
Labels: approved, lgtm, ok-to-test, size/XS

#1041 Documentation: Update out-of-date information in metering-config.md.
  Documentation/metering-config.md
Labels: approved, lgtm, size/XS

#1042 Updating s3 storage uri in documentation
  Documentation/metering-config.md
Labels: approved, lgtm, ok-to-test, size/XS

#1016 [release-4.2] bug 1766341: hack: Fix mirroring scripts now that internal image registry is different
  hack/mirror-ose-image.sh
  hack/mirror-ose-images-into-cluster.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
