Repository kube-reporting/metering-operator, pull requests merged in 2019-03, with the labels that each got.

#601 reporting-operator: use secret for token config
  Documentation/configuring-reporting-operator.md
  Documentation/metering-config.md
  charts/reporting-operator/templates/reporting-operator-config.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/templates/reporting-operator-prometheus-bearer-token-secrets.yaml
  charts/reporting-operator/values.yaml
Labels: approved, lgtm, size/M

#603 Update integration test scripts for origin CI
  Dockerfile.src
  charts/metering-ci/templates/metering.yaml
  hack/deploy-continuous-upgrade.sh
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/e2e-test-runner.sh
  hack/e2e.sh
  hack/install.sh
  hack/integration.sh
  hack/lib/init.sh
  hack/lib/tests.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  hack/uninstall.sh
Labels: approved, lgtm, size/M

#604 charts: Fix reporting-operator repo value in CI template
  charts/metering-ci/templates/metering.yaml
  hack/lib/init.sh
Labels: approved, lgtm, size/XS

#605 Add junit reports to unit tests
  .gitignore
  Dockerfile.src
  Makefile
  hack/unit.sh
Labels: approved, lgtm, size/M

#606 hack: improve capturing pod logs in e2e tests
  hack/capture-pod-logs.sh
  hack/e2e-test-runner.sh
  hack/lib/util.sh
  jenkins/vars/testRunner.groovy
Labels: approved, lgtm, size/L

#612 charts/reporting-operator: Fix variable for tokenSecret in deployment template
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
Labels: approved, lgtm, size/XS

#613 Fix panic when fetching datasource metrics caused by incorrect map key name
  pkg/operator/datasources.go
  pkg/operator/prestostore/prometheusmetric.go
  pkg/presto/util.go
Labels: approved, lgtm, size/M

#615 charts,manifests: Update generated metering CR used by scripts to use {} as default spec
  charts/helm-operator/templates/cr.yaml
  charts/helm-operator/values.yaml
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift-helm-operator-values.yaml
  manifests/deploy/openshift/helm-operator/metering.yaml
Labels: approved, lgtm, size/XS

#620 test/testhelpers: Handle when results have zero as comparison column
  test/testhelpers/assert.go
Labels: approved, lgtm, size/XS

#618 hack: Add script to update ReportDataSource fixtures
  hack/update-datasource-fixtures.sh
Labels: approved, lgtm, size/S

#619 Fix report dependency resolution
  pkg/operator/reporting/validate.go
  pkg/operator/reporting/validate_test.go
Labels: approved, lgtm, size/L

#621 images/helm-operator: Only store resource version after helm upgrade succeeds
  images/helm-operator/run-operator.sh
Labels: approved, lgtm, size/XS

#609 telemeter-reporting: add basic telemeter chart
  Documentation/configuring-telemeter.md
  Documentation/index.md
  charts/telemeter-reporting/Chart.yaml
  charts/telemeter-reporting/templates/datasources.yaml
  charts/telemeter-reporting/templates/prom-queries/machine-cpu-cores-by-cluster-id.yaml
  charts/telemeter-reporting/templates/report-queries/machine-cpu-cores-by-cluster-id.yaml
  charts/telemeter-reporting/values.yaml
Labels: approved, lgtm, size/L

#622 jenkins,hack: Improve test runner to collect more information at end of tests
  hack/e2e-test-runner.sh
  jenkins/vars/testRunner.groovy
Labels: approved, lgtm, size/L

#623 test: Remove -scheduled-report suffix from report result output files
  test/framework/report.go
Labels: approved, lgtm, size/XS

#610 Wait to run Reports until dependencies have data
  Documentation/report.md
  Documentation/rollup-reports.md
  charts/metering-ci/templates/metering.yaml
  hack/deploy-e2e.sh
  hack/e2e.sh
  hack/integration.sh
  hack/run-e2e-tests.sh
  hack/run-integration-tests.sh
  jenkins/vars/testRunner.groovy
  manifests/reports/cluster-capacity-daily.yaml
  manifests/reports/cluster-usage-daily.yaml
  manifests/reports/cluster-utilization-daily.yaml
  manifests/reports/cluster-utilization-hourly.yaml
  manifests/reports/namespace-usage-daily.yaml
  pkg/apis/metering/v1alpha1/report.go
  pkg/apis/metering/v1alpha1/report_datasource.go
  pkg/apis/metering/v1alpha1/util/report_util.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
  pkg/operator/http.go
  pkg/operator/operator.go
  pkg/operator/prestostore/importer.go
  pkg/operator/prestostore/query.go
  pkg/operator/query.go
  pkg/operator/queues.go
  pkg/operator/reporting/validate.go
  pkg/operator/reports.go
  test/e2e/main_test.go
  test/e2e/report_test.go
  test/framework/report.go
  test/integration/main_test.go
  test/integration/report_test.go
Labels: approved, lgtm, size/XXL

#626 test/integration: Remove -runonce suffix from integration test result output files
  test/integration/report_test.go
Labels: approved, lgtm, size/XS

#627 test/integration: Retrieve actual results before opening expected results file
  test/integration/report_test.go
Labels: approved, lgtm, size/XS

#629 pkg/operator: Fix panic when there are no metrics imported
  pkg/operator/datasources.go
Labels: approved, lgtm, size/XS

#630 test: Fix order of assert.Equal arguments
  test/testhelpers/assert.go
Labels: approved, lgtm, size/XS

#625 Update e2e for running against origin CI/4.0 clusters
  charts/metering-ci/templates/metering.yaml
  hack/e2e-test-runner.sh
  jenkins/vars/testRunner.groovy
  test/e2e/main_test.go
Labels: approved, lgtm, size/M

#631 hack/deploy.sh: Fix jq cannot iterate over null errors
  hack/deploy.sh
Labels: approved, lgtm, size/S

#628 Dockerfile.src,jenkins: Move checkout of code to happen via jenkins in the container
  Dockerfile.src
  Makefile
  jenkins/vars/testRunner.groovy
Labels: approved, lgtm, size/M

#624 reporting-operator: fix Prometheus token configuration
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/templates/reporting-operator-prometheus-bearer-token-secrets.yaml
Labels: approved, lgtm, size/S

#574 PVC Storage Used ReportGenerationQuery/Report
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-phase.yaml
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-usage.yaml
  charts/openshift-reporting/values.yaml
  test/e2e/main_test.go
  test/integration/main_test.go
  test/integration/testdata/datasources/node-allocatable-cpu-cores.json
  test/integration/testdata/datasources/node-allocatable-memory-bytes.json
  test/integration/testdata/datasources/node-capacity-cpu-cores.json
  test/integration/testdata/datasources/node-capacity-memory-bytes.json
  test/integration/testdata/datasources/persistentvolumeclaim-phase.json
  test/integration/testdata/datasources/persistentvolumeclaim-usage-bytes.json
  test/integration/testdata/datasources/pod-request-cpu-cores.json
  test/integration/testdata/datasources/pod-request-memory-bytes.json
  test/integration/testdata/datasources/pod-usage-cpu-cores.json
  test/integration/testdata/datasources/pod-usage-memory-bytes.json
  test/integration/testdata/reports/namespace-cpu-request.json
  test/integration/testdata/reports/namespace-cpu-usage.json
  test/integration/testdata/reports/namespace-memory-request.json
  test/integration/testdata/reports/namespace-memory-usage.json
  test/integration/testdata/reports/node-cpu-utilization.json
  test/integration/testdata/reports/node-memory-utilization.json
  test/integration/testdata/reports/persistentvolumeclaim-usage.json
  test/integration/testdata/reports/pod-cpu-request.json
  test/integration/testdata/reports/pod-cpu-usage.json
  test/integration/testdata/reports/pod-memory-request.json
  test/integration/testdata/reports/pod-memory-usage.json
Labels: approved, lgtm, size/XXL

#633 Update OLM CSV description.
  charts/helm-operator/templates/cr.yaml
  hack/create-deploy-manifests.sh
  hack/create-olm-manifests.sh
  hack/remove-helm-template-header.sed
  manifests/custom-resource-definitions/metering.crd.yaml
  manifests/custom-resource-definitions/prestotable.crd.yaml
  manifests/custom-resource-definitions/report.crd.yaml
  manifests/custom-resource-definitions/reportdatasource.crd.yaml
  manifests/custom-resource-definitions/reportgenerationquery.crd.yaml
  manifests/custom-resource-definitions/reportprometheusquery.crd.yaml
  manifests/custom-resource-definitions/storagelocation.crd.yaml
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift-olm-values.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-clusterrole.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-clusterrolebinding.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-role.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-rolebinding.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-service-account.yaml
  manifests/deploy/openshift/helm-operator/metering.yaml
  manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/openshift/olm/metering.operatorgroup.yaml
  manifests/deploy/openshift/olm/metering.package.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
Labels: approved, lgtm, size/L

#638 Improve validation of Report data dependency checks and fix runImmediately
  Documentation/report.md
  manifests/custom-resource-definitions/reportdatasource.crd.yaml
  pkg/apis/metering/v1alpha1/report_datasource.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
  pkg/operator/prestostore/query.go
  pkg/operator/reports.go
  test/integration/main_test.go
Labels: approved, lgtm, size/L

#637 charts/hdfs: Add hdfs label to hdfs resources
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/namenode-statefulset.yaml
Labels: approved, size/S

#632 Write resourceVersion used to Metering CR status
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
  Dockerfile.src
  charts/helm-operator/templates/deployment.yaml
  charts/helm-operator/values.yaml
  images/helm-operator/run-operator.sh
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#643 Documentation,pkg/operator: Make Report spec.reportingStart optional again.
  Documentation/report.md
  pkg/operator/reports.go
Labels: approved, lgtm, size/S

#642 pkg/operator: Allow triggering ReportDataSource collection for individual ReportDataSource
  pkg/operator/http.go
  pkg/operator/http_test.go
  pkg/operator/promsum.go
Labels: approved, lgtm, size/S

#644 hack: Update image tag used for origin CI
  hack/lib/tests.sh
Labels: approved, lgtm, size/XS

#645 manifests/deploy: Update min resources in Metering CSV
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
Labels: approved, size/XS

#647 manifests: Add example report to metering CSV
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#651 Update links to Presto documentation
  Documentation/metering-architecture.md
Labels: approved, lgtm, ok-to-test, size/XS

#650 charts/presto: Add initial support for configuring extra Presto connectors
  charts/presto/templates/presto-catalog-config-secret.yaml
  charts/presto/values.yaml
Labels: approved, lgtm, size/XS

#659 Jenkins Dev Doc Fix
  Documentation/dev/jenkins.md
Labels: approved, lgtm, size/XS

#658 Refine PVC Used
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-usage.yaml
  test/integration/main_test.go
  test/integration/testdata/reports/persistentvolumeclaim-usage.json
Labels: approved, lgtm, size/M

#657 Make running e2e/integration with local metering/reporting-operator possible
  Documentation/dev/developer-guide.md
  Makefile
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  charts/presto/values.yaml
  cmd/reporting-operator/start.go
  hack/deploy-e2e.sh
  hack/deploy.sh
  hack/e2e-test-runner.sh
  hack/e2e.sh
  hack/integration.sh
  hack/lib/init.sh
  hack/lib/tests.sh
  hack/run-e2e-tests.sh
  hack/run-integration-tests.sh
  hack/run-metering-operator-local.sh
  hack/run-reporting-operator-local.sh
  pkg/operator/operator.go
  pkg/operator/pprof.go
  pkg/operator/reports.go
  test/e2e/main_test.go
  test/framework/collect.go
  test/framework/db.go
  test/framework/framework.go
  test/framework/report.go
  test/framework/service.go
  test/integration/main_test.go
Labels: approved, lgtm, size/XL
