Repository kube-reporting/metering-operator, pull requests merged in 2019-07, with the labels that each got.

#799 roles/meteringconfig: Add MeteringConfig option `spec.logHelmTemplate` to log helm template task
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
Labels: approved, lgtm, size/XS

#801 Update example MeteringConfig manifests
  manifests/metering-config/custom-node-selectors.yaml
  manifests/metering-config/default-resource-limits.yaml
  manifests/metering-config/hdfs-storage.yaml
  manifests/metering-config/recommended-resource-limits.yaml
Labels: approved, size/L

#805 Fix ansible failures using /.ansible instead of $HOME
  images/metering-ansible-operator/ansible.cfg
Labels: approved, lgtm, size/XS

#787 images/metering-ansible-operator: Enable reporting-operator authProxy by default.
  Gopkg.lock
  Gopkg.toml
  charts/metering-ci/templates/metering.yaml
  hack/run-e2e-tests.sh
  hack/run-integration-tests.sh
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
  test/e2e/main_test.go
  test/framework/framework.go
  test/framework/service.go
  test/integration/main_test.go
  vendor/github.com/Masterminds/semver/LICENSE.txt
  vendor/github.com/Masterminds/sprig/LICENSE.txt
  vendor/github.com/aokoli/goutils/LICENSE.txt
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
Labels: approved, lgtm, size/XXL

#807 test/e2e: Fix race condition on Reporting resources being created
  test/e2e/report_test.go
Labels: approved, size/XS

#797 Update defaultMode of presto configmap
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#803 Support TLS from Hive Server to Hive metastore using ghostunnel
  charts/openshift-metering/templates/hive/hive-configmap.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-tls-secrets.yaml
  charts/openshift-metering/templates/hive/hive-server-metastore-tls-secrets.yaml
  charts/openshift-metering/templates/hive/hive-server-service.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-tls-secrets.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
Labels: approved, lgtm, size/L

#808 hack: Fix running e2e/integration locally
  hack/e2e.sh
  hack/integration.sh
  hack/run-e2e-tests.sh
  hack/run-integration-tests.sh
Labels: approved, lgtm, size/S

#802 images/metering-ansible-operator: Prefix TLS-related default variables with an underscore.
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
Labels: approved, lgtm, size/L

#810 Support configuring hive-server with authentication via ghostunnel
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-hive-auth-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-hive-tls-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml
  charts/openshift-metering/values.yaml
  cmd/reporting-operator/start.go
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#811 charts,images: Support for configuring Presto to use ghostunnel to authenticate to hive metastore
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-hive-metastore-tls-secrets.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
Labels: approved, lgtm, size/L

#812 charts/openshift-metering: Auto-configure default hive-host for reporting-operator
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/values.yaml
Labels: approved, lgtm, size/XS

#809 charts/openshift-metering: Set Presto property hive.collect-column-statistics-on-write=true
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
Labels: approved, lgtm, size/XS

#813 roles/meteringconfig: Fix meteringconfig_create_hive_aws_credentials condition
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/XS

#814 charts/openshift-metering: Enable the metering route by default.
  charts/openshift-metering/values.yaml
Labels: lgtm, size/XS

#800 charts,images: Support using both pre/post-kubernetes 1.14 metrics
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  charts/openshift-metering/templates/openshift-reporting/datasources/default-datasources.yaml
  charts/openshift-metering/values.yaml
  hack/deploy-e2e.sh
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
Labels: approved, lgtm, size/L

#806 Add hadoop-starting-config to hive, presto, hadoop
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
Labels: approved, lgtm, size/M

#816 images/metering-ansible-operator: Rename TLS override variables to avoid being printed.
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: size/XS

#815 Update relevant documentation and manifests to reflect the changes made to authProxy.
  Documentation/configuring-reporting-operator.md
  Documentation/dev/debugging.md
  Documentation/install-metering.md
  Documentation/manual-olm-install.md
  Documentation/using-metering.md
  Documentation/writing-custom-queries.md
  manifests/metering-config/advanced-auth.yaml
  manifests/metering-config/expose-route.yaml
Labels: lgtm, size/L

#817 Disable unauthenticated Hive ports when TLS is enabled
  charts/openshift-metering/templates/hive/hive-configmap.yaml
  charts/openshift-metering/templates/hive/hive-metastore-service.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-service.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
Labels: approved, lgtm, size/M

#819 charts/openshift-metering: Fix hive-server initContainers
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
Labels: approved, lgtm, size/XS

#823 charts/metering-ci: Set logHelmTemplate to true during CI runs
  charts/metering-ci/templates/metering.yaml
Labels: approved, lgtm, size/XS

#826 Standardize CPU_Core_Seconds
  Documentation/rollup-reports.md
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-cpu.yaml
Labels: approved, lgtm, size/S

#822 Fix issues with database/table cleanup
  pkg/hive/query.go
  pkg/operator/hivetables.go
  pkg/operator/operator.go
  pkg/operator/prestotables.go
  pkg/operator/queues.go
  pkg/operator/storagelocations.go
Labels: approved, lgtm, size/M

#824 Run `helm template` in `make verify`
  Makefile
Labels: approved, lgtm, size/XS

#827 images/metering-ansible-operator: Move all reporting-operator TLS-related tasks to its own task file and clean-up TLS-related tasks.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
Labels: approved, lgtm, size/L

#820 core-site.xml credentials injection
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/hadoop/hadoop-azure-credentials.yaml
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-azure-credentials-secret.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-azure-credentials-secret.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
Labels: approved, lgtm, size/L

#830 roles/meteringconfig: Switch to using assert module for validation of storage
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
Labels: approved, lgtm, size/S

#832 Rename the 'http' port name to 'api' in the reporting-operator service.
  Documentation/reportqueries.md
  Documentation/using-metering.md
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-service.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-route.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-service.yaml
Labels: approved, lgtm, size/M

#833 images/metering-ansible-operator: Update conditional to check if the 'resources' field is defined in the registered variable.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
Labels: approved, lgtm, size/XS

#828 hack: Delete PVCs during uninstall
  hack/lib/init.sh
  hack/uninstall.sh
Labels: approved, size/XS

#825 Enable TLS in the reporting-operator, Presto, and Hive by default.
  hack/run-reporting-operator-local.sh
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
  pkg/operator/operator.go
Labels: approved, lgtm, size/XL

#836 Dockerfile.metering-ansible-operator*: Fix entrypoint
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
Labels: approved, lgtm, size/XS

#834 Update the Report CRD to use OpenAPI V3 schema validation.
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/report.crd.yaml
Labels: approved, lgtm, size/XL

#837 charts/openshift-metering: Update presto-worker to use tls/auth and work with azure
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
Labels: approved, lgtm, size/M

#829 Azure settings overide
  Documentation/configuring-storage.md
  charts/openshift-metering/templates/hadoop/hadoop-azure-credentials.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  manifests/metering-config/azure-blob-storage.yaml
Labels: approved, lgtm, size/L

#839 Edits to OLM install doc
  Documentation/olm-install.md
Labels: approved, ok-to-test, size/M

#840 Documentation: Clarify that Metering only supports Amazon s3 in relevant sections.
  Documentation/configuring-storage.md
  Documentation/index.md
  Documentation/metering-config.md
Labels: approved, lgtm, size/S

#841 Documentation: Improve specifying inputs documentation
  Documentation/reportdatasources.md
  Documentation/reportqueries.md
  Documentation/reports.md
Labels: approved, lgtm, size/M

#843 Documentation: Fix broken link in reportdatasources.md.
  Documentation/reportdatasources.md
Labels: size/XS

#838 Update the ReportDataSource CRD to use the OpenAPI V3 schema validation.
  charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/reportdatasource.crd.yaml
Labels: approved, lgtm, size/L

#844 Documentation: Fix another broken link in reportdatasources.md.
  Documentation/reportdatasources.md
Labels: size/XS

#842 Documentation: Add troubleshooting for the metering-ansible-operator.
  Documentation/dev/debugging.md
  Documentation/install-metering.md
Labels: approved, size/M

#845 Dockerfile*,images: Fix metering-ansible-operator running in Openshift 3.x
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  images/metering-ansible-operator/scripts/add-label.sh
  images/metering-ansible-operator/scripts/entrypoint.sh
Labels: approved, lgtm, size/M

#835 Add validation for ReportQuery
  charts/metering-ansible-operator/templates/crds/reportquery.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/reportquery.crd.yaml
Labels: approved, lgtm, size/L

#846 Update ReportDataSource CRD to comply with k8s structural standards.
  charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/reportdatasource.crd.yaml
Labels: approved, lgtm, size/M

#850 Dockerfile.metering-ansible-operator*: Install openssl
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
Labels: approved, lgtm, size/XS

#847 charts/openshift-metering: Set bind host for hive server and metastore to 127.0.0.1 with TLS/auth enabled
  charts/openshift-metering/templates/hive/hive-configmap.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/values.yaml
Labels: approved, lgtm, size/M

#853 manifests/metering-config: Fix mis-identation in metastore-storage.yaml.
  manifests/metering-config/metastore-storage.yaml
Labels: size/S

#854 Improve running local tests
  Makefile
  hack/e2e-test-runner.sh
  hack/run-reporting-operator-local.sh
Labels: approved, lgtm, size/S

#855 manifests/metering-config: Remove the 'class: null' key from MeteringConfig examples.
  manifests/metering-config/hdfs-storage.yaml
  manifests/metering-config/metastore-storage.yaml
  manifests/metering-config/recommended-resource-limits.yaml
Labels: approved, lgtm, size/XS

#856 manifests/metering-config: Add 'spec.storage.type' field to shared-storage.yaml.
  manifests/metering-config/shared-storage.yaml
Labels: approved, lgtm, size/XS

#851 Add structural schema validation to the MeteringConfig CRD using OpenAPI V3.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/metering-ci/templates/metering.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/XXL

#857 Documentation: Fix configuring hive metastore with MySQL/PostgreSQL
  Documentation/configuring-hive-metastore.md
Labels: approved, lgtm, size/M

#860 roles/meteringconfig: Fix validating TLS configurations
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
Labels: approved, lgtm, size/M
