Repository kube-reporting/metering-operator, pull requests merged in 2019-06, with the labels that each got.

#734 fixed link to aws billing correlation
  Documentation/metering-architecture.md
Labels: needs-ok-to-test, size/XS

#729 charts/openshift-metering: Update the reporting-operator and Presto StatefulSets to use TLS when specified
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  cmd/reporting-operator/start.go
  images/helm-operator/deploy-resources.sh
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#735 Documentation: Update dates used to 2019
  Documentation/api.md
  Documentation/install-metering.md
  Documentation/reports.md
  Documentation/rollup-reports.md
  Documentation/using-metering.md
Labels: approved, size/S

#736 Remove metering-helm-operator Dockerfiles
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
Labels: approved, lgtm, size/XS

#738 charts: Fix missing newline in presto configs
  charts/openshift-metering/templates/presto/presto-common-config.yaml
Labels: approved, lgtm, size/XS

#730 Remove data_start and data_end columns from all ReportQueries and documentation
  Documentation/api.md
  Documentation/reports.md
  Documentation/rollup-reports.md
  charts/openshift-metering/templates/openshift-reporting/report-queries/aws-billing.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/node-cpu.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/node-memory.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/persistentvolumeclaim-request.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-cpu-aws.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-cpu.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-memory-aws.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-memory.yaml
  test/integration/testdata/reports/namespace-cpu-request.json
  test/integration/testdata/reports/namespace-cpu-usage.json
  test/integration/testdata/reports/namespace-memory-request.json
  test/integration/testdata/reports/namespace-memory-usage.json
  test/integration/testdata/reports/namespace-persistentvolumeclaim-usage.json
  test/integration/testdata/reports/node-cpu-utilization.json
  test/integration/testdata/reports/node-memory-utilization.json
  test/integration/testdata/reports/persistentvolumeclaim-capacity.json
  test/integration/testdata/reports/persistentvolumeclaim-usage.json
  test/integration/testdata/reports/pod-cpu-request.json
  test/integration/testdata/reports/pod-cpu-usage.json
  test/integration/testdata/reports/pod-memory-request.json
  test/integration/testdata/reports/pod-memory-usage.json
Labels: approved, lgtm, size/L

#737 charts: Add ReservedCodeCacheSize and jdk.nio.maxCachedBufferSize to presto JVM options
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
Labels: approved, lgtm, size/XS

#739 Add support for configuring TLS authentication for Presto components by providing pre-existing secrets containing server, client, and CA resources.
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  cmd/reporting-operator/start.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#728 Support configuring default component images from environment variables to metering-ansible-operator
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/M

#740 charts,hack: Set presto resource requests lower and remove limits for CI tests
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  hack/deploy-e2e.sh
Labels: approved, lgtm, size/S

#742 Update and normalize outdated import identifiers for the metering v1alpha package
  pkg/operator/aws_usage_hive.go
  pkg/operator/datasources.go
  pkg/operator/hive_test.go
  pkg/operator/hivetables.go
  pkg/operator/http.go
  pkg/operator/http_test.go
  pkg/operator/prestotables.go
  pkg/operator/promsum.go
  pkg/operator/queues.go
  pkg/operator/reporting/templates_test.go
  pkg/operator/reporting/validate.go
  pkg/operator/reportingutil/util.go
  pkg/operator/reportquery.go
  pkg/operator/reports.go
  pkg/operator/reports_test.go
  pkg/operator/storage.go
  pkg/operator/storagelocations.go
  test/e2e/main_test.go
  test/e2e/report_test.go
  test/framework/datasource.go
  test/framework/framework.go
  test/framework/report.go
  test/testhelpers/helpers.go
Labels: approved, lgtm, size/XL

#743 charts/openshift-metering: Fix the ordering of TLS/Auth tasks in the presto-common-config.yaml.
  charts/openshift-metering/templates/presto/presto-common-config.yaml
Labels: approved, lgtm, size/XS

#746 metering-ansible-operator: Use different loop_var for prune_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
Labels: approved, lgtm, size/XS

#745 metering-ansible-operator: Install tini to cleanup zombie processes created by ansible
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  hack/ocp-util/redhat.repo
Labels: approved, lgtm, size/S

#748 Stop using async ansible tasks
  images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
Labels: approved, lgtm, size/M

#750 charts: Set java HeapDumpPath and ErrorFile for JVM based components
  charts/openshift-metering/templates/hdfs/hdfs-configmap.yaml
  charts/openshift-metering/templates/hdfs/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/presto/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
Labels: approved, lgtm, size/S

#751 Update the Presto and reporting-operator charts to handle a user providing client/server certificates that were signed by different CAs.
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  cmd/reporting-operator/start.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#752 *: Reorganize hdfs to part of a hadoop sub-component for better alignment with configuration usage
  charts/openshift-metering/templates/hadoop/hadoop-aws-credentials.yaml
  charts/openshift-metering/templates/hadoop/hadoop-configmap.yaml
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-serviceaccount.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  manifests/metering-config/s3-storage.yaml
  manifests/metering-config/shared-storage.yaml
Labels: approved, lgtm, size/XL

#754 Update Presto and reporting-operator resources to reflect changes made to values.yaml
  charts/openshift-metering/templates/presto/presto-auth-secrets.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-tls-secrets.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-tls-secrets.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
Labels: approved, lgtm, size/L

#753 Update references to hdfs configuration in MeteringConfig
  Documentation/configuring-storage.md
  charts/metering-ci/templates/metering.yaml
  manifests/metering-config/s3-storage.yaml
  manifests/metering-config/shared-storage.yaml
Labels: approved, lgtm, size/M

#756 charts: Replace scripted jvm max heap configuration with built-in JVM container support
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/presto/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/values.yaml
Labels: approved, lgtm, size/L

#757 pkg/operator: Never stop re queuing StorageLocations
  pkg/operator/queues.go
  pkg/operator/storagelocations.go
Labels: approved, lgtm, size/S

#763 hack/e2e-test-runner.sh: Capture MeteringConfig resource at end of tests
  hack/e2e-test-runner.sh
Labels: approved, lgtm, size/S

#764 roles/meteringconfig: Move namespace into separate label to shorten prune label value length
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
Labels: approved, lgtm, size/XS

#762 Fix lookup of DataSource table name in Prometheus store/fetch API
  pkg/operator/datasources.go
  pkg/operator/http.go
  pkg/operator/http_test.go
  pkg/operator/operator.go
  pkg/operator/promsum.go
  pkg/operator/reportingutil/util.go
  pkg/operator/reports.go
  pkg/presto/util.go
  test/framework/datasource.go
  test/framework/prestotables.go
Labels: approved, lgtm, size/L

#767 charts: Fix missing quotes around new env var options
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-server-statefulset.yaml
Labels: approved, lgtm, size/S

#766 charts: HDFS: Fix toplogy script location
  charts/openshift-metering/templates/hadoop/hadoop-configmap.yaml
Labels: approved, lgtm, size/XS

#768 charts/openshift-metering: Update the annotations used in the Presto coordinator/worker statefulsets to use the secret template hashes.
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
Labels: approved, lgtm, size/S

#760 Disable HDFS by default and wait for user to configure storage
  Documentation/common-configuration.md
  Documentation/configuring-hdfs.md
  Documentation/configuring-hive-metastore.md
  Documentation/configuring-storage.md
  Documentation/index.md
  Documentation/install-metering.md
  Documentation/storagelocations.md
  charts/metering-ci/templates/metering.yaml
  charts/openshift-metering/templates/metering/default-storage-location.yaml
  charts/openshift-metering/templates/presto/_hive_helpers.tpl
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-shared-volume-pvc.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-aws-credentials-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  manifests/metering-config/default.yaml
  manifests/metering-config/hdfs-storage.yaml
  manifests/metering-config/metastore-storage.yaml
  manifests/metering-config/s3-storage.yaml
  manifests/metering-config/shared-storage.yaml
  test/integration/main_test.go
Labels: approved, lgtm, size/XL

#770 metering-ansible-operator: Support provisioning metering storage S3 bucket
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  Documentation/aws/read-write-create.json
  Documentation/configuring-storage.md
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  manifests/metering-config/s3-storage.yaml
Labels: approved, lgtm, size/L

#765 charts,hack: Bump pod resources limits
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  charts/openshift-metering/values.yaml
  hack/deploy-e2e.sh
Labels: approved, lgtm, size/L

#772 metering-ansible-operator: Use recursive=true in combine() when getting hive storage type
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
Labels: approved, lgtm, size/XS

#775 roles/meteringconfig: Use CR's spec.storage combined with defaults for doing storage overrides
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/S

#769 Enable TLS and client-side authentication in Presto and reporting-operator by default.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  charts/metering-ci/templates/metering.yaml
  charts/openshift-metering/templates/presto/presto-auth-secrets.yaml
  charts/openshift-metering/templates/presto/presto-tls-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-tls-secrets.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
Labels: approved, lgtm, size/L

#777 Documentation: Update misleading configuration of authProxy fields.
  Documentation/configuring-reporting-operator.md
Labels: lgtm, size/XS

#776 charts,roles/meterinconfig: Fix bucket configuration handling
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/S

#778 roles/meteringconfig: Add reconcile_metering.yml to reconcile task
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, lgtm, size/XS

#780 Enable the ansible-operator to store Root CA data in a secret by default
  charts/openshift-metering/templates/metering/metering-root-ca-secret.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_openssl.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
Labels: approved, lgtm, size/L

#781 Allow running reporting-operator locally against TLS secured Presto
  cmd/reporting-operator/start.go
  hack/run-reporting-operator-local.sh
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#771 charts,images,manifests: Update reporting-operator configuration schema
  Documentation/configuring-aws-billing.md
  Documentation/configuring-storage.md
  charts/metering-ci/templates/metering.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-authenticated-emails-secret.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-cookie-secret.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-htpasswd-secret.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-auth-proxy-rbac.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-aws-credentials-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-cluster-monitoring-view-rbac.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-auth-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-presto-tls-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-prometheus-bearer-token-secrets.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-prometheus-certificate-authority-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-service.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-tls-secrets.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  manifests/metering-config/advanced-auth.yaml
  manifests/metering-config/aws-billing.yaml
  manifests/metering-config/custom-node-selectors.yaml
  manifests/metering-config/default-resource-limits.yaml
  manifests/metering-config/expose-route.yaml
  manifests/metering-config/recommended-resource-limits.yaml
Labels: approved, lgtm, size/XL

#785 Documentation: Update the command used to run Presto queries to reflect Presto TLS being enabled by default.
  Documentation/dev/debugging.md
Labels: size/XS

#790 fixed input names
  manifests/reports/cluster-usage-daily.yaml
Labels: ok-to-test, size/XS

#773 Add TLS to Hive Metastore
  charts/openshift-metering/templates/presto/hive-metastore-service.yaml
  charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml
  charts/openshift-metering/values.yaml
Labels: approved, lgtm, size/M

#784 convert hadoop-config from configmap to secret
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/hadoop/hadoop-config.yaml
  charts/openshift-metering/templates/hadoop/hadoop-configmap.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/presto/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
Labels: size/L

#791 images/metering-ansible-operator: Fix root_ca_secret_exists variable when meteringconfig_tls_enabled is false.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
Labels: approved, lgtm, size/XS

#783 Update Presto/Hive MeteringConfig schema
  Documentation/configuring-aws-billing.md
  Documentation/configuring-hive-metastore.md
  Documentation/configuring-storage.md
  charts/metering-ci/templates/metering.yaml
  charts/openshift-metering/templates/hadoop/hadoop-aws-credentials.yaml
  charts/openshift-metering/templates/hadoop/hadoop-config.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/_hive_helpers.tpl
  charts/openshift-metering/templates/hive/hive-aws-credentials-secret.yaml
  charts/openshift-metering/templates/hive/hive-configmap.yaml
  charts/openshift-metering/templates/hive/hive-jmx-config.yaml
  charts/openshift-metering/templates/hive/hive-metastore-pvc.yaml
  charts/openshift-metering/templates/hive/hive-metastore-service.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-service.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-serviceaccount.yaml
  charts/openshift-metering/templates/hive/hive-shared-volume-pvc.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/hive-metastore-pvc.yaml
  charts/openshift-metering/templates/presto/hive-shared-volume-pvc.yaml
  charts/openshift-metering/templates/presto/presto-auth-secrets.yaml
  charts/openshift-metering/templates/presto/presto-aws-credentials-secret.yaml
  charts/openshift-metering/templates/presto/presto-catalog-config-secret.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-tls-secrets.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  manifests/metering-config/aws-billing.yaml
  manifests/metering-config/default.yaml
  manifests/metering-config/s3-storage.yaml
Labels: approved, lgtm, size/XXL

#794 charts/openshift-metering: Add missing hive-metastore TLS secret volume
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
Labels: approved, lgtm, size/XS

#792 Dockerfile.src,hack: Remove stern
  Dockerfile.src
  hack/e2e-test-runner.sh
  hack/run-reporting-operator-local.sh
Labels: approved, lgtm, size/S

#786 Update openshift-reporting MeteringConfig schema
  charts/openshift-metering/templates/metering/default-storage-location.yaml
  charts/openshift-metering/templates/openshift-reporting/_reporting_helpers.tpl
  charts/openshift-metering/templates/openshift-reporting/datasources/default-datasources.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
Labels: approved, lgtm, size/L

#793 charts,images,manifests: Update MeteringConfig CRD API version from v1alpha1 to v1
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/metering-ansible-operator/templates/operator/meteringconfig.yaml
  charts/metering-ansible-operator/values.yaml
  images/metering-ansible-operator/watches.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/metering-config/advanced-auth.yaml
  manifests/metering-config/aws-billing.yaml
  manifests/metering-config/custom-node-selectors.yaml
  manifests/metering-config/default-resource-limits.yaml
  manifests/metering-config/default.yaml
  manifests/metering-config/expose-route.yaml
  manifests/metering-config/hdfs-storage.yaml
  manifests/metering-config/latest-versions.yaml
  manifests/metering-config/metastore-storage.yaml
  manifests/metering-config/recommended-resource-limits.yaml
  manifests/metering-config/s3-storage.yaml
  manifests/metering-config/shared-storage.yaml
Labels: approved, lgtm, size/M
