Repository kube-reporting/metering-operator, pull requests merged in 2019-04, with the labels that each got.

#660 Refine PVC Capacity
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-capacity.yaml
  test/integration/testdata/reports/persistentvolumeclaim-capacity.json
Labels: approved, lgtm, size/S

#667 Bump version to 0.14.0-latest
  VERSION
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/metering.0.14.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.0.14.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.package.yaml
Labels: approved, lgtm, size/XL

#663 Update OLM install instructions for latest 4.0 builds
  Documentation/olm-install.md
  charts/metering-olm/templates/catalogsourceconfig.yaml
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/olm/metering.catalogsourceconfig.yaml
Labels: approved, lgtm, size/S

#664 test/e2e: Check ReportDataSources for EarliestImportedMetricTime to determine reportStart
  test/e2e/main_test.go
  test/e2e/report_test.go
  test/framework/datasource.go
Labels: approved, lgtm, size/M

#670 Documentation: Add section on how versions work with manual installs
  Documentation/manual-install.md
Labels: approved, lgtm, size/XS

#672 charts/openshift-reporting: Fix PVC usage query
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-usage.yaml
  test/integration/testdata/reports/persistentvolumeclaim-usage.json
Labels: approved, lgtm, size/S

#661 pkg/operator: Fix metering health check table name
  pkg/operator/operator.go
  pkg/operator/reporting/health.go
Labels: approved, size/S

#671 cmd/reporting-operator: Fix port conflict with auth-proxy
  cmd/reporting-operator/start.go
Labels: approved, lgtm, size/XS

#669 reporting-operator: allow custom prometheus CA
  Documentation/configuring-reporting-operator.md
  Documentation/configuring-telemeter.md
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/templates/reporting-operator-prometheus-certificate-authority-config.yaml
  charts/reporting-operator/values.yaml
Labels: approved, lgtm, size/M

#668 Documentation: Add documentation covering how to install using the Openshift OperatorHub
  Documentation/manual-olm-install.md
  Documentation/olm-install.md
Labels: approved, lgtm, size/L

#654 namespace persistentvolumeclaim usage
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-request.yaml
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-usage.yaml
  test/e2e/main_test.go
  test/integration/main_test.go
  test/integration/testdata/reports/namespace-persistentvolumeclaim-usage.json
Labels: approved, lgtm, size/M

#676 OWNERS: Add timflannagan1 as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#675 Documentation: remove ansible install option
  Documentation/ansible-install.md
  Documentation/index.md
  Documentation/install-metering.md
Labels: approved, lgtm, size/M

#674 Improve test output
  hack/e2e-test-runner.sh
  pkg/operator/http.go
  test/framework/datasource.go
  test/framework/db.go
  test/framework/report.go
  test/framework/reportgenerationquery.go
  test/integration/main_test.go
  test/testhelpers/assert.go
Labels: approved, lgtm, size/M

#677 Documentation: Update links/commands and make minor adjustments.
  Documentation/dev/debugging.md
  Documentation/using-metering.md
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, size/M

#678 Documentation: Update example in writing-custom-queries.md to include…
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, size/M

#679 little typo in this yaml
  manifests/metering-config/shared-storage.yaml
Labels: needs-ok-to-test, size/S

#683 *: Remove jenkins ci code and documentation
  Documentation/dev/developer-guide.md
  Documentation/dev/jenkins.md
  Documentation/dev/release.md
  jenkins/build.groovy
  jenkins/continuous-upgrade.groovy
  jenkins/main.groovy
  jenkins/openshift-continuous-upgrade.groovy
  jenkins/openshift-e2e.groovy
  jenkins/openshift-integration.groovy
  jenkins/vars/notifyBuild.groovy
  jenkins/vars/testRunner.groovy
Labels: approved, lgtm, size/XL

#684 Use origin images by default and remove extra/unused makefile targets/scripts
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
  Dockerfile.src
  Documentation/dev/builds.md
  Makefile
  VERSION
  charts/hdfs/values.yaml
  charts/helm-operator/values.yaml
  charts/openshift-metering/values.yaml
  charts/presto/values.yaml
  charts/reporting-operator/values.yaml
  hack/generate-metering-manifests.sh
  hack/lib/init.sh
  hack/lib/version.sh
  hack/print-version.sh
  hack/render-metering-chart-override-values.sh
  hack/render-olm-override-values.sh
  hack/run-metering-operator-local.sh
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/metering.0.13.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.0.14.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.0.14.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.4.1.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/metering.package.yaml
  manifests/metering-config/latest-versions.yaml
Labels: approved, lgtm, size/XXL

#686 Dockerfile.src,hack: Add operator-courier to src image
  Dockerfile.src
  hack/scl-operator-courier.sh
Labels: approved, size/S

#685 Update OLM manifest generation for marketplace publishing
  Dockerfile.metering-operator
  Dockerfile.metering-operator.rhel
  Documentation/dev/developer-guide.md
  Makefile
  charts/metering-olm/templates/clusterserviceversion.yaml
  hack/create-metering-manifests.sh
  hack/create-olm-manifests.sh
  hack/deploy-custom.sh
  hack/lib/init.sh
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-clusterrole.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-clusterrolebinding.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-role.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-rolebinding.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-service-account.yaml
  manifests/deploy/openshift/metering-operator/metering.yaml
  manifests/deploy/openshift/olm/bundle/metering.crd.yaml
  manifests/deploy/openshift/olm/bundle/metering.package.yaml
  manifests/deploy/openshift/olm/bundle/meteringoperator.v4.1.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/reportgenerationquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/reportprometheusquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/storagelocation.crd.yaml
Labels: approved, lgtm, size/L

#689 manifests/deploy: Fix subscription channel
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
Labels: approved, size/XS

#692 Fix metering-operator RHEL/OCP Dockerfile
  Dockerfile.metering-operator.rhel
Labels: approved, size/XS

#693 Refactor getter logic into test helpers
  pkg/operator/reporting/getters.go
  pkg/operator/reporting/validate.go
  pkg/operator/reporting/validate_test.go
  test/testhelpers/helpers.go
Labels: approved, lgtm, size/L

#695 Makefile,manifests/deploy: Use v4.0 image tag for quay upstream images
  Makefile
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/meteringoperator.v4.1.0.clusterserviceversion.yaml
Labels: approved, size/S

#696 manifests,charts: Fix metering package bundle for marketplace
  charts/metering-olm/templates/clusterserviceversion.yaml
  manifests/custom-resource-definitions/reportgenerationquery.crd.yaml
  manifests/deploy/common-olm-values.yaml
  manifests/deploy/openshift/olm/bundle/meteringoperator.v4.1.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/reportgenerationquery.crd.yaml
Labels: approved, size/S

#690 Documentation: Fix phrasing and punctuation.
  Documentation/metering-architecture.md
Labels: size/M

#691 pkg/operator: Fix small linting errors and remove unneeded code.
  pkg/operator/datasources.go
  pkg/operator/http.go
  pkg/operator/reports.go
  pkg/operator/storage.go
Labels: size/M

#694 Fix go vet errors
  Makefile
  pkg/operator/datasources.go
  pkg/operator/operator.go
  pkg/operator/prestostore/prometheusmetric.go
  pkg/operator/reports.go
Labels: approved, size/S

#688 Use `namespace` label if `exported_namespace` metric label is missing in PVC queries
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-capacity.yaml
  charts/openshift-reporting/templates/report-queries/persistentvolumeclaim-usage.yaml
Labels: approved, lgtm, size/XS

#698 Makefile,manifests: Use 4.1 for metering-operator image tag
  Makefile
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift/metering-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/meteringoperator.v4.1.0.clusterserviceversion.yaml
Labels: approved, size/S

#687 pkg/operator: Fix metrics importing tracking
  pkg/operator/prestostore/query.go
Labels: approved, lgtm, size/S

#700 charts/reporting-operator: Skip auth for /healthy and /ready endpoints
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
Labels: approved, lgtm, size/XS

#699 charts/*: Fix invalid configurations in helm charts.
  charts/hdfs/templates/datanode-statefulset.yaml
  charts/hdfs/templates/service-account.yaml
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/templates/hive-serviceaccount.yaml
  charts/presto/templates/presto-coordinator-deployment.yaml
  charts/presto/templates/presto-serviceaccount.yaml
  charts/presto/templates/presto-worker-deployment.yaml
Labels: approved, lgtm, size/XS
