Repository kube-reporting/metering-operator, pull requests merged in 2019-10, with the labels that each got.

#961 cmd,pkg/deploy: Add function to the deploy package that reads the YAML manifests and builds up objects.
  cmd/deploy-metering/main.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/helpers.go
  pkg/operator/deploy/install.go
  pkg/operator/deploy/uninstall.go
Labels: approved, lgtm, size/XL

#958 bug 1757547: charts/openshift-metering: Update cpu/memory usage promqueries to handle many to many matching error
  charts/openshift-metering/values.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#965 pkg/operator,cmd/deploy-metering: Move reading of MeteringConfig into main package
  cmd/deploy-metering/main.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/helpers.go
  pkg/operator/deploy/install.go
  pkg/operator/deploy/uninstall.go
Labels: approved, lgtm, size/L

#957 Add HTTP endpoint to render ReportQueries
  pkg/operator/http.go
  pkg/operator/http_test.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/L

#967 cmd,pkg/deploy: Initialize clientsets outside of the deploy package.
  cmd/deploy-metering/main.go
  pkg/operator/deploy/deploy.go
Labels: approved, lgtm, size/M

#966 charts,manifests: Enforce OLM package channel name is a string
  charts/metering-ansible-operator/ocp-testing-values.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/metering.package.yaml
  manifests/deploy/openshift/olm/bundle/metering.package.yaml
  manifests/deploy/upstream/olm/bundle/metering.package.yaml
Labels: approved, lgtm, size/S

#970 Documentation: Update link to kube-prometheus.
  Documentation/configuring-reporting-operator.md
Labels: approved, lgtm, size/XS

#968 hack: Fix mirroring scripts now that internal image registry is different
  hack/get-metering-package-images.sh
  hack/mirror-ose-image.sh
  hack/mirror-ose-images-into-cluster.sh
Labels: approved, lgtm, size/M

#969 charts/openshift-metering: Fix sum fields on pod-usage-memory-bytes
  charts/openshift-metering/values.yaml
Labels: approved, lgtm, size/XS

#972 test/reportingframework: Rename the framework package to reportingframework.
  test/e2e/main_test.go
  test/e2e/report_test.go
  test/integration/main_test.go
  test/integration/report_test.go
  test/reportingframework/collect.go
  test/reportingframework/datasource.go
  test/reportingframework/db.go
  test/reportingframework/framework.go
  test/reportingframework/prestotables.go
  test/reportingframework/report.go
  test/reportingframework/reportquery.go
  test/reportingframework/service.go
Labels: approved, lgtm, size/L

#973 test: Remove redundant code block from the reportingframework constructor.
  test/e2e/main_test.go
  test/integration/main_test.go
  test/reportingframework/framework.go
Labels: approved, lgtm, size/S

#980 pkg/apis: Update various fields in the MeteringConfig API.
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#981 test/reportingframework: Stat the report output directory.
  test/reportingframework/framework.go
Labels: approved, lgtm, size/XS

#984 pkg/deploy: Support passing extra namespace labels for use in testing.
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/install.go
Labels: approved, lgtm, size/S

#987 hack: Change junit report file name for e2e/integration tests
  hack/e2e-test-runner.sh
  hack/e2e.sh
  hack/integration.sh
Labels: approved, lgtm, size/XS

#979 test,hack: Refactor the e2e package to use the deploy metering package.
  hack/e2e.sh
  hack/run-test-cleanup.sh
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
  test/testhelpers/helpers.go
Labels: approved, lgtm, size/XL

#994 test/deployframework: Ensure the overrided reporting-operator image isn't empty.
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/M

#998 cmd,pkg/deploy: Remove the nested logging and fix linting errors.
  cmd/deploy-metering/main.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/helpers.go
  pkg/operator/deploy/install.go
  pkg/operator/deploy/uninstall.go
Labels: approved, lgtm, size/L

#976 bugfix: add missing comment clause to create table sql
  pkg/presto/util.go
Labels: approved, lgtm, ok-to-test, size/XS

#988 bug 1763306: Fix setting default fileformat for Hive tables
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/hive/hive-configmap.yaml
  charts/openshift-metering/values.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1001 Add unit test ensuring metering-operator and reporting-operator image repo/tags are set correctly
  pkg/operator/deploy/deploy.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/XL

#986 hack: Fix mirroring to work for digests
  hack/get-metering-package-images.sh
  hack/mirror-ose-images-into-cluster.sh
Labels: approved, lgtm, size/M

#989 charts/openshift-metering: Support annotations on service accounts
  charts/openshift-metering/templates/hadoop/hdfs-serviceaccount.yaml
  charts/openshift-metering/templates/hive/hive-serviceaccount.yaml
  charts/openshift-metering/templates/presto/presto-serviceaccount.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-serviceaccount.yaml
Labels: approved, lgtm, size/S

#990 charts,manifests: Support configuring reporting-operator securityContext
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
Labels: approved, lgtm, size/L

#1008 bug 1763303: Fix AWS billing ReportDataSource functionality
  charts/metering-ansible-operator/templates/crds/hive.crd.yaml
  charts/openshift-metering/templates/openshift-reporting/datasources/aws-datasources.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/aws-billing.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/hive.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/hive.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/hive.crd.yaml
  pkg/operator/aws_usage_hive.go
  pkg/operator/hivetables.go
  pkg/operator/reporting/db.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#992 hack,test,Makefile: Consolidate the e2e and integration testing suites.
  Makefile
  hack/delete-ns.sh
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/deploy.sh
  hack/e2e-test-runner.sh
  hack/e2e.sh
  hack/integration.sh
  hack/run-e2e-tests.sh
  hack/unit.sh
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
  test/e2e/reporting_produces_correct_data_for_input_tests.go
  test/e2e/reports_produce_data_tests.go
  test/e2e/testdata/datasources/node-allocatable-cpu-cores.json
  test/e2e/testdata/datasources/node-allocatable-memory-bytes.json
  test/e2e/testdata/datasources/node-capacity-cpu-cores.json
  test/e2e/testdata/datasources/node-capacity-memory-bytes.json
  test/e2e/testdata/datasources/persistentvolumeclaim-capacity-bytes.json
  test/e2e/testdata/datasources/persistentvolumeclaim-phase.json
  test/e2e/testdata/datasources/persistentvolumeclaim-usage-bytes.json
  test/e2e/testdata/datasources/pod-request-cpu-cores.json
  test/e2e/testdata/datasources/pod-request-memory-bytes.json
  test/e2e/testdata/datasources/pod-usage-cpu-cores.json
  test/e2e/testdata/datasources/pod-usage-memory-bytes.json
  test/e2e/testdata/reports/namespace-cpu-request.json
  test/e2e/testdata/reports/namespace-cpu-usage.json
  test/e2e/testdata/reports/namespace-memory-request.json
  test/e2e/testdata/reports/namespace-memory-usage.json
  test/e2e/testdata/reports/namespace-persistentvolumeclaim-usage.json
  test/e2e/testdata/reports/node-cpu-utilization.json
  test/e2e/testdata/reports/node-memory-utilization.json
  test/e2e/testdata/reports/persistentvolumeclaim-capacity.json
  test/e2e/testdata/reports/persistentvolumeclaim-usage.json
  test/e2e/testdata/reports/pod-cpu-request.json
  test/e2e/testdata/reports/pod-cpu-usage.json
  test/e2e/testdata/reports/pod-memory-request.json
  test/e2e/testdata/reports/pod-memory-usage.json
  test/integration/report_test.go
  test/reportingframework/framework.go
Labels: approved, lgtm, size/XXL

#991 charts,manifests: Support configuring Presto hive.s3.use-instance-credentials Hive catalog config property
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/values.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
Labels: approved, lgtm, size/M
