Repository kube-reporting/metering-operator, pull requests merged in 2019-08, with the labels that each got.

#858 Add TLS sub-schema validation to the MeteringConfig CRD.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/hive/hive-metastore-tls-secrets.yaml
  charts/openshift-metering/templates/hive/hive-server-metastore-tls-secrets.yaml
  charts/openshift-metering/templates/hive/hive-server-tls-secrets.yaml
  charts/openshift-metering/values.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/XXL

#863 Updates docs: oc create project-> new-project
  Documentation/olm-install.md
Labels: approved, lgtm, size/XS

#864 Documentation,manifests; Add minimal HDFS configuration example in developer-guide docs
  Documentation/dev/developer-guide.md
  manifests/metering-config/hdfs-minimal.yaml
Labels: approved, lgtm, size/S

#861 Update the storage sub-schema validation to restrict mutually exclusive fields from being set.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/L

#867 Documentation: Use namespace instead of projects for OLM install
  Documentation/olm-install.md
Labels: approved, size/XS

#866 charts/openshift-metering: use correct variable for checking if Hadoop config is available to presto
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
Labels: approved, lgtm, size/XS

#865 Add properties and update validation to spec.hive.storage in the MeteringConfig CRD.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/M

#870 roles/meteringconfig: Verify azure storage credentials secret is specified
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, lgtm, size/S

#872 validate fsGroup as integer
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: needs-ok-to-test, size/S

#875 Add int64 format to the fsGroup properties.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: size/XS

#869 metering-ansible-operator: Move tini into $PATH and update entrypoint
  Dockerfile.metering-ansible-operator
  images/metering-ansible-operator/scripts/entrypoint.sh
Labels: approved, lgtm, size/XS

#877 Documentation: Indicate where the metering repo must be located to build correctly
  Documentation/dev/developer-guide.md
Labels: approved, lgtm, size/S

#879 charts,manifests: Region is not required for S3 storage
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/XS

#876 manifests: Add more possible storage options into default.yaml MeteringConfig
  manifests/metering-config/default.yaml
Labels: approved, lgtm, size/S

#881 jq -r fixes to docs and a typo fix
  Documentation/configuring-reporting-operator.md
  Documentation/metering-architecture.md
  Documentation/using-metering.md
  Documentation/writing-custom-queries.md
Labels: lgtm, size/XS

#882 Documentation: Rename metering route variable to match the other references.
  Documentation/configuring-reporting-operator.md
Labels: size/XS

#880 charts,manifests: Update validation to the reporting-operator authProxy section.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/L

#883 charts,manifests: Update validation of the schedule section in the Report CRD.
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/report.crd.yaml
Labels: approved, lgtm, size/L

#884 fixes writing-custom-queries.md doc for schema use
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, size/XS

#868 Update OLM/Marketplace 4.2 package
  Documentation/install-metering.md
  Documentation/manual-olm-install.md
  Documentation/olm-install.md
  charts/metering-ansible-operator/templates/_helpers.tpl
  charts/metering-ansible-operator/templates/olm/art.yaml
  charts/metering-ansible-operator/templates/olm/catalogsourceconfig.yaml
  charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml
  charts/metering-ansible-operator/templates/olm/operatorgroup.yaml
  charts/metering-ansible-operator/templates/olm/subscription.yaml
  charts/metering-ansible-operator/values.yaml
  hack/create-metering-manifests.sh
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.1/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.1/image-references
  manifests/deploy/openshift/olm/bundle/4.1/metering.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.1/meteringoperator.v4.1.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.1/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.1/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.1/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.1/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.1/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
  manifests/deploy/openshift/olm/bundle/package.yaml
  manifests/deploy/openshift/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/openshift/olm/metering.operatorgroup.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
Labels: approved, lgtm, size/XL

#885 charts,manifests: Update the validation of the top-level permissions key in the MeteringConfig CRD.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/L

#859 Add support for Google Cloud Storage with Json keyfile as auth
  Documentation/configuring-storage.md
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/hadoop/hadoop-config.yaml
  charts/openshift-metering/templates/hadoop/hadoop-gcs-credentials.yaml
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-azure-credentials-secret.yaml
  charts/openshift-metering/templates/hive/hive-gcs-credentials-secret.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-gcs-credentials-secret.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
  manifests/metering-config/gcs-storage.yaml
Labels: approved, lgtm, size/XL

#888 charts,manifests: Remove the required properties in the Report CRD.
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/report.crd.yaml
Labels: approved, lgtm, size/M

#886 Add OpenAPI V3 schema validation to the PrestoTable CRD.
  Documentation/prestotables.md
  charts/metering-ansible-operator/templates/crds/prestotable.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/prestotable.crd.yaml
  manifests/reports/cluster-capacity-daily.yaml
  manifests/reports/cluster-usage-daily.yaml
Labels: approved, lgtm, size/L

#889 fix for azure in meteringconfig.crd
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
Labels: approved, lgtm, size/M

#890 Update OCP metering-ansible-operator Root CA CSR creation
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
Labels: approved, lgtm, size/S

#893 added regex to append '/' at the end of bucketname if none was provided
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/XS

#894 migrating manifests from saas-metering repo
  manifests/deploy/openshift/telemeter/list.yaml
Labels: approved, lgtm, size/XL

#895 pkg/operator: Iterate over columns to ensure consistent values ordering
  pkg/operator/http.go
Labels: approved, lgtm, size/XS

#892 S3 compatible storage
  Documentation/configuring-storage.md
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/hadoop/hadoop-s3-compatible-credentials.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/_hive_helpers.tpl
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-s3-compatible-credentials-secret.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-s3-compatible-credentials-secret.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
  manifests/metering-config/s3-compatible-storage.yaml
Labels: approved, lgtm, size/XL

#898 Dockerfile.src: Run yum clean and remove yum cache before running yum
  Dockerfile.src
Labels: approved, lgtm, size/XS

#897 Add OpenAPIV3 schema validation to the HiveTable CRD.
  Documentation/hivetables.md
  charts/metering-ansible-operator/templates/crds/hive.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/hive.crd.yaml
Labels: approved, lgtm, size/XL

#899 hack: Support passing $HOME/.minkube to run-metering-operator-local.sh docker container
  hack/run-metering-operator-local.sh
Labels: approved, size/S

#901 Documentation: Update the prometheus nested fields.
  Documentation/configuring-reporting-operator.md
Labels: approved, lgtm, size/M

#905 hack: Update the target directory location for the minikube directory.
  hack/run-metering-operator-local.sh
Labels: size/XS

#906 Helm template doc add
  Documentation/dev/developer-guide.md
Labels: size/XS

#903 Add OpenAPIV3 schema validation to the StorageLocation CRD.
  Documentation/storagelocations.md
  charts/metering-ansible-operator/templates/crds/storagelocation.crd.yaml
  charts/openshift-metering/values.yaml
  manifests/deploy/openshift/metering-ansible-operator/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/storagelocation.crd.yaml
Labels: approved, lgtm, size/L

#907 charts,images,manifests: Set ghostunnel image from envvars
  charts/metering-ansible-operator/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.2/image-references
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#909 Dockerfile.metering-ansible-operator: Ensure ansible 2.8 or newer
  Dockerfile.metering-ansible-operator
Labels: approved, lgtm, size/XS

#908 Remove *_DEPLOY_REPO and *_DEPLOY_TAG variables
  Documentation/dev/developer-guide.md
  Makefile
  charts/metering-ci/templates/metering.yaml
  hack/create-metering-manifests.sh
  hack/deploy-continuous-upgrade.sh
  hack/deploy-custom.sh
  hack/deploy-e2e.sh
  hack/e2e.sh
  hack/generate-metering-manifests.sh
  hack/install.sh
  hack/integration.sh
  hack/lib/init.sh
  hack/lib/tests.sh
  hack/render-ansible-operator-override-values.sh
Labels: approved, lgtm, size/L

#912 Dockerfiles: yum clean and rm yum cache before yum install
  Dockerfile.metering-ansible-operator
  Dockerfile.reporting-operator.okd
Labels: approved, lgtm, size/XS

#911 Bug 1744314: Use 4.2 oauth-proxy image and support override image via envvar for ART OLM manifest manipulation
  charts/metering-ansible-operator/values.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.2/image-references
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#913 hack: Remove unnecessary CRD_DIR variable
  hack/install.sh
  hack/lib/init.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  hack/uninstall.sh
Labels: approved, lgtm, size/S

#916 Documentation: Improve documentation on create secrets for storage credentials
  Documentation/configuring-storage.md
Labels: approved, lgtm, size/M

#902 Automate manifest saas metering
  charts/metering-ansible-operator/ocp-testing-values.yaml
  charts/metering-ansible-operator/templates/saas-metering/list.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  hack/create-metering-manifests.sh
  hack/deploy-custom.sh
  hack/generate-metering-manifests.sh
  hack/lib/init.sh
  manifests/deploy/openshift/telemeter/list.yaml
Labels: approved, lgtm, size/XXL

#917 hack: Update the OLM uninstall to delete the CSV created from the subscription.
  hack/olm-uninstall.sh
Labels: approved, lgtm, size/XS

#915 hack,charts,manifests: Skip generating the ART package for non-ocp manifests.
  charts/metering-ansible-operator/ocp-testing-values.yaml
  charts/metering-ansible-operator/templates/olm/art.yaml
  charts/metering-ansible-operator/templates/olm/operatorgroup.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  hack/create-metering-manifests.sh
  hack/generate-metering-manifests.sh
  manifests/deploy/ocp-testing/olm/bundle/art.yaml
  manifests/deploy/ocp-testing/olm/bundle/metering.package.yaml
  manifests/deploy/ocp-testing/olm/metering.operatorgroup.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
  manifests/deploy/openshift/olm/bundle/metering.package.yaml
  manifests/deploy/openshift/olm/metering.operatorgroup.yaml
  manifests/deploy/upstream/olm/bundle/art.yaml
  manifests/deploy/upstream/olm/bundle/metering.package.yaml
  manifests/deploy/upstream/olm/metering.operatorgroup.yaml
Labels: approved, lgtm, size/M
