Repository kube-reporting/metering-operator, pull requests merged in 2019-09, with the labels that each got.

#918 Support HTTPs with self-signed certs on s3Compatible storage endpoints
  Documentation/configuring-storage.md
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/hadoop/hadoop-s3-compatible-ca-secret.yaml
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-s3-compatible-ca-secret.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-s3-compatible-ca-secret.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.2/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.2/meteringconfig.crd.yaml
  manifests/metering-config/s3-compatible-storage.yaml
Labels: approved, lgtm, size/XL

#926 Update hivetables.md to use reporting-operator
  Documentation/hivetables.md
Labels: needs-ok-to-test, size/XS

#924 Documentation: Fix architecture docs
  Documentation/metering-architecture.md
Labels: approved, lgtm, size/S

#928 Fix kube version detection and installation of defaultReportDataSources
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml
Labels: approved, lgtm, size/XS

#925 Always import full chunks when querying metrics
  pkg/operator/datasources.go
  pkg/operator/prestostore/importer.go
  pkg/operator/prestostore/query.go
  pkg/operator/prestostore/query_test.go
  pkg/operator/promsum.go
Labels: approved, lgtm, size/L

#920 Add the MeteringConfig resource to the metering client.
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/register.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/metering/v1/fake/fake_metering_client.go
  pkg/generated/clientset/versioned/typed/metering/v1/fake/fake_meteringconfig.go
  pkg/generated/clientset/versioned/typed/metering/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/metering/v1/metering_client.go
  pkg/generated/clientset/versioned/typed/metering/v1/meteringconfig.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/metering/v1/interface.go
  pkg/generated/informers/externalversions/metering/v1/meteringconfig.go
  pkg/generated/listers/metering/v1/expansion_generated.go
  pkg/generated/listers/metering/v1/meteringconfig.go
Labels: approved, lgtm, size/XL

#932 Fix image overrides from environment for components
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/L

#936 Documentation/dev: Add developer documentation for using Metering with NooBaa
  Documentation/dev/noobaa.md
Labels: approved, lgtm, size/L

#937 pkg/operator: Queue hive StorageLocation when missing DatabaseName
  pkg/operator/aws_usage_hive.go
  pkg/operator/datasources.go
  pkg/operator/reports.go
Labels: approved, lgtm, size/XS

#935 pkg/deploy: Add the cluster-monitoring label when creating an Openshift namespace.
  pkg/operator/deploy/create.go
Labels: approved, lgtm, size/M

#939 charts,manifests: Fix name of OLM package filename in art.yaml
  charts/metering-ansible-operator/templates/olm/art.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
Labels: approved, lgtm, size/XS

#933 Document testing OCP install of metering using ART published OLM manifest bundle
  Documentation/dev/mirroring-ocp-images.md
  Documentation/dev/testing-ocp-images.md
  Documentation/dev/testing-olm-ocp-install.md
  charts/metering-ansible-operator/ocp-testing-values.yaml
  hack/get-metering-package-images.sh
  hack/mirror-ose-image.sh
  hack/mirror-ose-images-into-cluster.sh
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.2/image-references
  manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#930 charts,manifests: Update documentation links in OCP OLM packages to use docs.openshift.com
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#942 pkg/apis: Update fields and json encodings in the MeteringConfig structure.
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#943 images,charts: Fix default image overrides from preventing overriding image in MeteringConfig
  charts/openshift-metering/templates/_ghostunnel_helpers.tpl
  charts/openshift-metering/templates/hadoop/_hadoop_helpers.tpl
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/_hive_helpers.tpl
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/_helpers.tpl
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm, size/L

#941 hack: Remove unneeded logic from deploy-custom.sh
  hack/deploy-custom.sh
Labels: approved, lgtm, size/S

#934 Add a cobra cli that manages the deployment process of metering.
  Makefile
  cmd/deploy-metering/main.go
  cmd/deploy/main.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/helpers.go
  pkg/operator/deploy/install.go
  pkg/operator/deploy/uninstall.go
Labels: approved, lgtm, size/XL

#946 pkg/operator: Queue Reports and ReportDataSource dependents of ReportDataSources after updating status
  pkg/operator/datasources.go
Labels: approved, lgtm, size/S

#945 Gopkg.toml: Ignore test2json
  Gopkg.toml
Labels: approved, lgtm, size/XS

#944 hack,Makefile: Update the deploy scripts to use the deploy-metering binary.
  Makefile
  hack/deploy.sh
  hack/lib/util.sh
  hack/run-metering-operator-local.sh
Labels: approved, do-not-merge/hold, lgtm, size/M

#949 bug 1755130: charts,manifests: Fix link to about report docs in OLM CSV package description
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#951 *: Update to go 1.12
  Dockerfile.reporting-operator
  Dockerfile.reporting-operator.okd
  Dockerfile.reporting-operator.rhel
  Dockerfile.src
  Documentation/dev/developer-guide.md
  hack/ocp-util/ocp-image-pull-and-rename.sh
  pkg/operator/prestostore/importer.go
Labels: approved, do-not-merge/hold, lgtm, size/S

#954 Set XDG_CACHE_HOME to /tmp
  Dockerfile.reporting-operator
  Dockerfile.reporting-operator.okd
  Dockerfile.reporting-operator.rhel
  Dockerfile.src
Labels: approved, size/XS

#955 pkg/operator: Fix unit tests after Go 1.12 upgrade
  pkg/operator/reporting/templates_test.go
Labels: approved, size/S

#960 bug 1756548: charts/openshift-metering: Fix kube 1.14 metrics queries
  charts/openshift-metering/values.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#956 cmd,pkg/deploy: Support passing an object to the MeteringConfig resource.
  cmd/deploy-metering/main.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/helpers.go
  pkg/operator/deploy/install.go
  pkg/operator/deploy/uninstall.go
Labels: approved, lgtm, size/M
