Repository kube-reporting/metering-operator, pull requests merged in 2019-05, with the labels that each got.

#697 pkg/operator: Refactor the checks/validations in runReport into individual functions and add their unit tests.
  pkg/operator/http_test.go
  pkg/operator/reporting/validate_test.go
  pkg/operator/reports.go
  pkg/operator/reports_test.go
  test/testhelpers/helpers.go
Labels: approved, lgtm, size/L

#702 pkg/operator: Refactor getting a report's reportPeriod into its own function and add unit tests.
  pkg/operator/reports.go
  pkg/operator/reports_test.go
Labels: approved, lgtm, size/L

#706 reporting-operator: Rename ReportMetricImportStatus to ReportMetricsImportStatus
  pkg/apis/metering/v1alpha1/report_datasource.go
  pkg/apis/metering/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
  pkg/operator/queues.go
  pkg/operator/reports.go
  test/e2e/report_test.go
Labels: approved, lgtm, size/S

#707 Documentation: Fix unrendered links and rename report.md -> reports.md
  Documentation/index.md
  Documentation/metering-architecture.md
  Documentation/reportqueries.md
  Documentation/reports.md
  Documentation/using-metering.md
  Documentation/writing-custom-queries.md
Labels: lgtm, size/S

#708 pkg/operator: Do not return uppercased column types
  pkg/operator/reportingutil/util.go
Labels: approved, lgtm, size/XS

#712 pkg/apis: Fix prometheusMetricsImportStatus json struct field
  pkg/apis/metering/v1alpha1/report_datasource.go
  test/integration/main_test.go
Labels: approved, lgtm, size/XS

#714 charts: Fix custom Prometheus CA configmap
  charts/openshift-metering/templates/reporting-operator/reporting-operator-prometheus-certificate-authority-config.yaml
Labels: approved, lgtm, size/XS

#716 hack: Just use kubectl to create the namespace instead of `oc project`
  hack/openshift-install.sh
Labels: approved, size/XS

#715 metering-operator: Grant access to openshift authorization apis
  charts/metering-helm-operator/values.yaml
  manifests/deploy/openshift/metering-helm-operator/metering-operator-role.yaml
  manifests/deploy/openshift/olm/bundle/4.1/meteringoperator.v4.1.0.clusterserviceversion.yaml
Labels: approved, size/XS

#713 Documentation: Fix links that weren't updated after last architecture change.
  Documentation/reportdatasources.md
  Documentation/reportqueries.md
Labels: size/S

#717 charts/openshift-metering: Configure Presto blackhole, memory, tpcds, and tpch connectors
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-catalog-config-secret.yaml
Labels: approved, lgtm, size/S

#701 Add Metering Ansible Operator
  Dockerfile.metering-ansible-operator
  Makefile
  images/metering-ansible-operator/build/test-framework/Dockerfile
  images/metering-ansible-operator/build/test-framework/ansible-test.sh
  images/metering-ansible-operator/deploy/crds/metering_v1alpha1_meteringconfig_cr.yaml
  images/metering-ansible-operator/deploy/crds/metering_v1alpha1_meteringconfig_crd.yaml
  images/metering-ansible-operator/deploy/operator.yaml
  images/metering-ansible-operator/deploy/role.yaml
  images/metering-ansible-operator/deploy/role_binding.yaml
  images/metering-ansible-operator/deploy/service_account.yaml
  images/metering-ansible-operator/roles/meteringconfig/README.md
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/handlers/main.yml
  images/metering-ansible-operator/roles/meteringconfig/meta/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml
  images/metering-ansible-operator/roles/meteringconfig/vars/main.yml
  images/metering-ansible-operator/watches.yaml
Labels: approved, lgtm, size/L

#719 pkg/operator: Reduces template rendering use of report query fields.
  pkg/operator/datasources.go
  pkg/operator/reporting/templates.go
  pkg/operator/reportingutil/util.go
  pkg/operator/reports.go
Labels: approved, lgtm, size/M

#722 pkg/operator: Fix ownerReference GVK for ReportQueryView ReportDataSources
  pkg/operator/datasources.go
Labels: approved, lgtm, size/XS

#710 pkg/operator: Add unit-tests for ReportQuery templating.
  pkg/operator/datasources.go
  pkg/operator/http.go
  pkg/operator/http_test.go
  pkg/operator/promsum.go
  pkg/operator/reporting/templates.go
  pkg/operator/reporting/templates_test.go
  pkg/operator/reportingutil/util.go
  pkg/operator/reports.go
  test/testhelpers/helpers.go
Labels: approved, lgtm, size/XL

#724 pkg/operator: Fix ownerReference GVK for ReportQueryView ReportDataSources
  pkg/operator/datasources.go
Labels: approved, lgtm, size/XS

#725 metering-ansible-operator: Run deploy-resources.sh in meteringconfig role
  Dockerfile.metering-ansible-operator
  images/helm-operator/deploy-resources.sh
  images/metering-ansible-operator/deploy/clusterrole.yaml
  images/metering-ansible-operator/deploy/clusterrolebinding.yaml
  images/metering-ansible-operator/deploy/role.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml
  images/metering-ansible-operator/watches.yaml
Labels: approved, lgtm, size/L

#726 *: Use 4.2 images by default
  Makefile
  charts/metering-helm-operator/values.yaml
  charts/openshift-metering/values.yaml
  hack/lib/init.sh
  manifests/deploy/openshift/metering-helm-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.2/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/image-references
  manifests/deploy/openshift/olm/bundle/4.2/metering.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.2/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.2/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/package.yaml
Labels: approved, lgtm, size/XL

#727 hack/ocp-util,Makefile: Update utilities/files for local ocp image builds
  Makefile
  hack/ocp-util/ocp-build-vars.sh
  hack/ocp-util/ocp-image-pull-and-rename.sh
  hack/ocp-util/redhat.repo
Labels: approved, lgtm, size/M

#720 reporting-operator: Switch to github.com/taozle/go-hive-driver and use database/sql for getting hive queryer
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/reporting-operator/start.go
  pkg/db/interface.go
  pkg/hive/connection.go
  pkg/hive/database.go
  pkg/hive/table.go
  pkg/operator/operator.go
  pkg/operator/reporting/db.go
  thrift/TCLIService.thrift
  vendor/github.com/emersion/go-sasl/LICENSE
  vendor/github.com/emersion/go-sasl/anonymous.go
  vendor/github.com/emersion/go-sasl/external.go
  vendor/github.com/emersion/go-sasl/login.go
  vendor/github.com/emersion/go-sasl/plain.go
  vendor/github.com/emersion/go-sasl/sasl.go
  vendor/github.com/emersion/go-sasl/xoauth2.go
  vendor/github.com/taozle/go-hive-driver/config.go
  vendor/github.com/taozle/go-hive-driver/conn.go
  vendor/github.com/taozle/go-hive-driver/connector.go
  vendor/github.com/taozle/go-hive-driver/dial.go
  vendor/github.com/taozle/go-hive-driver/driver.go
  vendor/github.com/taozle/go-hive-driver/rows.go
  vendor/github.com/taozle/go-hive-driver/sasl_transport.go
  vendor/github.com/taozle/go-hive-driver/thriftlib/GoUnusedProtection__.go
  vendor/github.com/taozle/go-hive-driver/thriftlib/hive-consts.go
  vendor/github.com/taozle/go-hive-driver/thriftlib/hive.go
  vendor/github.com/taozle/go-hive-driver/value.go
Labels: approved, size/XXL

#732 charts/openshift-metering: Update the Presto components to use a StatefulSet instead of a Deployment.
  charts/openshift-metering/templates/presto/presto-coordinator-deployment.yaml
  charts/openshift-metering/templates/presto/presto-service.yaml
  charts/openshift-metering/templates/presto/presto-worker-deployment.yaml
Labels: approved, lgtm, size/S
