Repository kube-reporting/metering-operator, pull requests merged in 2019-01, with the labels that each got.

#548 charts/presto: Set imagePullSecrets for hive statefulsets
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
Labels: size/XS

#549 charts/hdfs: Support older jq versions
  charts/hdfs/templates/configmap.yaml
Labels: size/XS

#546 Improve authorization support
  Documentation/configuring-reporting-operator.md
  charts/openshift-metering/templates/rolebindings.yaml
  charts/openshift-metering/templates/roles.yaml
  charts/openshift-metering/values.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/values.yaml
  manifests/metering-config/advanced-auth.yaml
  manifests/metering-config/expose-route.yaml
Labels: size/L

#551 manifests,charts,hack: Move ServiceMonitors to openshift-metering chart
  charts/openshift-metering/templates/monitoring-rbac.yaml
  charts/openshift-metering/templates/presto-service-monitor.yaml
  charts/openshift-metering/templates/reporting-operator-service-monitor.yaml
  charts/openshift-metering/values.yaml
  hack/openshift-install.sh
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift/alm/metering.0.12.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-role.yaml
Labels: size/M

#556 Update the Metering side for OLM inclusion
  charts/metering-alm/templates/clusterserviceversion.yaml
  charts/metering-alm/templates/package-v1.yaml
  charts/metering-alm/templates/package.yaml
  charts/metering-alm/templates/subscription.yaml
  hack/create-alm-manifests.sh
  manifests/deploy/common-alm-values.yaml
  manifests/deploy/openshift/alm/metering.0.12.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
Labels: size/M

#552 cmd,pkg,test: Reporting-operator: support watching all namespaces and namespace besides pod namespace
  Documentation/api.md
  Documentation/configuring-reporting-operator.md
  Documentation/reportgenerationqueries.md
  Documentation/using-metering.md
  Documentation/writing-custom-queries.md
  charts/helm-operator/templates/clusterrole.yaml
  charts/helm-operator/templates/clusterrolebinding.yaml
  charts/helm-operator/values.yaml
  charts/metering-alm/templates/clusterserviceversion.yaml
  charts/reporting-operator/templates/reporting-operator-auth-proxy-rbac.yaml
  charts/reporting-operator/templates/reporting-operator-config.yaml
  charts/reporting-operator/templates/reporting-operator-deployment.yaml
  charts/reporting-operator/templates/reporting-operator-rbac.yaml
  charts/reporting-operator/values.yaml
  cmd/reporting-operator/start.go
  hack/create-alm-manifests.sh
  hack/create-deploy-manifests.sh
  hack/install.sh
  hack/lib/init.sh
  hack/openshift-install.sh
  hack/openshift-uninstall.sh
  hack/uninstall.sh
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift/alm/metering.0.12.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-clusterrole.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-clusterrolebinding.yaml
  manifests/rbac/reporting-operator-clusterrole.yaml
  pkg/operator/datasources.go
  pkg/operator/hive.go
  pkg/operator/http.go
  pkg/operator/http_test.go
  pkg/operator/operator.go
  pkg/operator/prestotables.go
  pkg/operator/promsum.go
  pkg/operator/query.go
  pkg/operator/queues.go
  pkg/operator/reporting/report_generator.go
  pkg/operator/reporting/report_generator_test.go
  pkg/operator/reporting/templates.go
  pkg/operator/reporting/validate_test.go
  pkg/operator/reportingutil/util.go
  pkg/operator/reports.go
  pkg/operator/storage.go
  test/framework/collect.go
  test/framework/db.go
  test/framework/report.go
  test/testhelpers/helpers.go
Labels: size/XL

#562 Release 0.13.0
  VERSION
  manifests/deploy/openshift/alm/metering.0.13.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.0.13.0.clusterserviceversion.yaml
  manifests/deploy/openshift/alm/metering.package.yaml
  manifests/deploy/openshift/alm/metering.subscription.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/XL

#561 charts/presto: Support configuring java heap ratio on hive pods
  charts/presto/templates/_helpers.tpl
  charts/presto/templates/hive-metastore-statefulset.yaml
  charts/presto/templates/hive-server-statefulset.yaml
  charts/presto/values.yaml
Labels: size/S

#565 Update metering-operator to support watching multiple namespaces
  charts/helm-operator/templates/deployment.yaml
  charts/helm-operator/values.yaml
  hack/custom-metering-operator-install-wrapper.sh
  hack/install.sh
  hack/render-helm-operator-override-values.sh
  hack/run-metering-operator-local.sh
  images/helm-operator/run-operator.sh
  manifests/deploy/common-helm-operator-values.yaml
  manifests/deploy/openshift/alm/metering.0.13.0-latest.clusterserviceversion.yaml
  manifests/deploy/openshift/helm-operator/metering-operator-deployment.yaml
Labels: size/L

#564 Documentation,manifests: Document tuning metering components
  Documentation/README.md
  Documentation/common-configuration.md
  Documentation/index.md
  Documentation/metering-config.md
  Documentation/tuning.md
  manifests/metering-config/default-resource-limits.yaml
  manifests/metering-config/recommended-resource-limits.yaml
Labels: size/L, skip-all

#570 Bugfix: PVC Request ReportGenerationQuery Storageclass
  charts/openshift-reporting/templates/report-queries/pod-volume-request.yaml
Labels: size/XS

#569 Documentation: Fix rollup-reporting document example
  Documentation/rollup-reports.md
Labels: size/M
