Repository kube-reporting/metering-operator, pull requests merged in 2019-12, with the labels that each got.

#1048 charts,manifests: Update the metering package bundle to 4.4.
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/metering.package.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/upstream/olm/bundle/4.4/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/image-references
  manifests/deploy/upstream/olm/bundle/4.4/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.4/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/reportquery.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/storagelocation.crd.yaml
  manifests/deploy/upstream/olm/bundle/metering.package.yaml
Labels: approved, lgtm, size/XXL

#1049 charts,manifests: Update the art.yaml to 4.4.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.4/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/image-references
  manifests/deploy/openshift/olm/bundle/4.4/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.4/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
Labels: approved, lgtm, size/XXL

#1050 Fix configuring-hive-metastore.md
  Documentation/configuring-hive-metastore.md
Labels: approved, needs-ok-to-test, size/S

#1047 test/deployframework: Fix the logging message for where the metering-operator local logs are stored.
  test/deployframework/local.go
Labels: approved, lgtm, size/XS

#1046 Dockerfile,images: Manage the MeteringConfig status directly.
  Dockerfile.metering-ansible-operator
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/update_meteringconfig_status.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
  images/metering-ansible-operator/watches.yaml
Labels: approved, lgtm, size/XL

#1052 manifests: Stop maintaining a 4.3 bundle for the release-4.4.
  manifests/deploy/ocp-testing/olm/bundle/4.3/hive.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/image-references
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringoperator.v4.3.0.clusterserviceversion.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/prestotable.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/report.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/reportdatasource.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/reportquery.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/image-references
  manifests/deploy/openshift/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/meteringoperator.v4.3.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.3/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.3/storagelocation.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/image-references
  manifests/deploy/upstream/olm/bundle/4.3/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/meteringoperator.v4.3.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.3/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/reportquery.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.3/storagelocation.crd.yaml
Labels: approved, lgtm, size/XXL

#1054 pkg/deploy: Remove unused code discovered by linter.
  pkg/deploy/deploy.go
  pkg/deploy/helpers.go
Labels: approved, lgtm, size/S

#1053 Documentation/dev: Update the debugging.md file.
  Documentation/dev/debugging.md
Labels: approved, lgtm, size/M

#1057 charts,manifests: Update the csv's container image field to use the 4.4 tag instead of latest.
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#1055 hack: Remove the outdated integration test bash script.
  hack/run-integration-tests.sh
Labels: approved, lgtm, size/M

#1060 OWNERS: Add bparees to approvers list.
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1061 OWNERS: Update the release 4.3 owners.
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1059 Bug 1782237: Fix the invalid tag used in the CSV container image field.
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.3/meteringoperator.v4.3.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.3/meteringoperator.v4.3.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.3/meteringoperator.v4.3.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1056 Dockerfile: Update the maintainers to be the mailing list.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  Dockerfile.reporting-operator
  Dockerfile.reporting-operator.okd
  Dockerfile.reporting-operator.rhel
Labels: approved, lgtm, size/S

#1017 MC-720 Making Prometheus connector available to Presto
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-catalog-config-secret.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-prometheus-auth.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringconfig.crd.yaml
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#1062 OWNERS: Update the release-4.2 owners.
  OWNERS
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#1063 hack,Makefile,test: Support running the e2e suite in a more dev-friendly configuration.
  Makefile
  hack/e2e.sh
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/M

#1064 Initial e2e for prom connector
  test/e2e/main_test.go
  test/e2e/presto_prometheus_connector_up_test.go
Labels: approved, lgtm, size/L
