Repository kube-reporting/metering-operator, pull requests merged in 2020-09, with the labels that each got.

#1382 hack,Makefile: Explicitly run any of the test/deployframework tests.
  Makefile
  hack/e2e.sh
Labels: approved, bugzilla/valid-bug, lgtm

#1391 test/e2e: Fix the Prometheus store API endpoint
  test/reportingframework/db.go
Labels: approved, bugzilla/valid-bug, lgtm

#1385 Bug 1874652: Add the secretName property to the MeteringConfig CRD schema validation.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1386 Bug 1872425: Fix missing namespaces in the case where usage exists without request
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-cpu.yaml
  charts/openshift-metering/templates/openshift-reporting/report-queries/pod-memory.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1393 Bug 1872080: Remove copy directive for the non-existent scripts directory
  Dockerfile.metering-ansible-operator.rhel8
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1398 Dockerfile: Update the project root build images
  Dockerfile.src
Labels: approved

#1399 Dockerfile: Use the origin-release golang base image
  Dockerfile.src
Labels: approved

#1400 hack: Move the test/deployframework tests to the unit test script
  hack/e2e.sh
  hack/unit.sh
Labels: approved

#1402 test/e2e: Reduce reporting-operator CPU requests and rename metering tests
  test/e2e/main_test.go
  test/e2e/manifests/meteringconfigs/nfs.yaml
  test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-disabled.yaml
  test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-enabled.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1367 e2e: report expires with no dependency & does not expire with dependency
  pkg/operator/http_test.go
  pkg/operator/reporting/templates_test.go
  pkg/operator/reporting/validate_test.go
  pkg/operator/reports_test.go
  test/e2e/main_test.go
  test/e2e/report_dynamic_input_data_test.go
  test/e2e/report_static_input_data_test.go
  test/reportingframework/report.go
  test/testhelpers/helpers.go
Labels: approved, bugzilla/valid-bug, lgtm

#1395 hack,test: Deploy metering using the index image packaging method
  hack/e2e.sh
  test/deployframework/registry.go
  test/e2e/main_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#1405 Bug 1881650: Ensure the volumeName label is not empty in the kube_persistentvolumeclaim_info metric
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  charts/openshift-metering/values.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1406 Documentation/dev: Specify the metering database instead of the default in debugging.md
  Documentation/dev/debugging.md
Labels: approved, bugzilla/valid-bug, lgtm
