Repository kube-reporting/metering-operator, pull requests merged in 2020-11, with the labels that each got.

#1426 Dockerfile: Use the upstream ansible-operator base image
  Dockerfile.metering-ansible-operator
Labels: approved

#1427 test/e2e: Add a post-install test that ensures the Metering leader election ConfigMap is present
  test/e2e/ensure_leader_election_configmap_is_created_test.go
  test/e2e/main_test.go
Labels: approved, lgtm

#1414 cmd/reporting-operator: Minor changes to the main package
  cmd/reporting-operator/start.go
Labels: approved, lgtm

#1394 go.*,vendor: Bump to v1.18.6 kube* that contains the ResourceVersionTooLarge fix
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/parser.go
  vendor/modules.txt
Labels: approved, lgtm

#1431 Dockerfile: Add the opm CLI to interact with operator-registry and build indexes of operator content
  Dockerfile.src
Labels: approved

#1429 olm_deploy: Remove the unused scripts directory
  olm_deploy/scripts/init-bundle-registry.sh
Labels: approved, lgtm

#1430 Add support for mirroring changes to the Metering bundle manifests
  Makefile
  hack/generate-metering-manifests.sh
  hack/lib/init.sh
  olm_deploy/bundle/manifests/hive.crd.yaml
  olm_deploy/bundle/manifests/meteringconfig.crd.yaml
  olm_deploy/bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml
  olm_deploy/bundle/manifests/prestotable.crd.yaml
  olm_deploy/bundle/manifests/report.crd.yaml
  olm_deploy/bundle/manifests/reportdatasource.crd.yaml
  olm_deploy/bundle/manifests/reportquery.crd.yaml
  olm_deploy/bundle/manifests/storagelocation.crd.yaml
Labels: approved, lgtm

#1434 olm_deploy/manifests: Remove the unused registry Deployment and Service
  olm_deploy/manifests/deployment.yaml
  olm_deploy/manifests/service.yaml
Labels: approved, lgtm

#1435 Remove the olm_deploy directory and migrate the Metering bundle to the bundle directory
  Dockerfile.bundle
  bundle/manifests/hive.crd.yaml
  bundle/manifests/meteringconfig.crd.yaml
  bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml
  bundle/manifests/prestotable.crd.yaml
  bundle/manifests/report.crd.yaml
  bundle/manifests/reportdatasource.crd.yaml
  bundle/manifests/reportquery.crd.yaml
  bundle/manifests/storagelocation.crd.yaml
  bundle/metadata/annotations.yaml
  hack/enable-machine-autoscaling.sh
  hack/lib/init.sh
  test/e2e/manifests/machines/clusterautoscaler.yaml
  test/e2e/manifests/machines/machineautoscaler.yaml
Labels: approved, lgtm

#1437 Update project status in README
  README.md
Labels: approved

#1440 test/e2e: Avoid using the fatal logrus level in the main_test.go
  test/e2e/main_test.go
Labels: approved, lgtm

#1441 Avoid using docker.io images in the build_root image
  Dockerfile.src
Labels: approved

#1442 hack,Dockerfile: Stop installing the operator-courier package
  Dockerfile.src
  hack/scl-operator-courier.sh
Labels: approved

#1439 charts,manifests: Fix the invalid metering image tag in the upstream CSV manifest
  bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1445 hack: Gather all the PackageManifests in a test cluster
  hack/gather-registry-artifacts.sh
Labels: approved, lgtm

#1443 Bug 1898373: Fix the HiveTable status.partitions schema definition
  bundle/manifests/hive.crd.yaml
  charts/metering-ansible-operator/templates/crds/hive.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.7/hive.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.7/hive.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1447 Dockerfile,Makefile: Add a make target that verifies the metering bundle contents are valid
  Dockerfile.src
  Makefile
Labels: approved

#1448 pkg/operator: Cleanup the isReportFinished helper function
  pkg/operator/reports.go
Labels: approved, lgtm

#1450 Bug 1900125: Stop vendoring the module_utils/crypto.py Ansible library
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel8
  images/metering-ansible-operator/roles/meteringconfig/module_utils/crypto.py
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1451 Dockerfile: Bump the Golang version in the reporting-operator base image
  Dockerfile.reporting-operator
Labels: approved, lgtm

#1455 Dockerfile.src: Avoid using the latest Helm image tag
  Dockerfile.src
Labels: approved

#1436 upstream reports expiration field docs
  Documentation/reports.md
Labels: approved, lgtm

#1454 go.mod,vendor: Bump the Go version in go.mod
  go.mod
  vendor/modules.txt
Labels: approved, lgtm
