Repository kube-reporting/metering-operator, pull requests merged in 2020-04, with the labels that each got.

#1157 manifests: Re-sync manifest/deploy files after reverting PR#1143.
  manifests/deploy/openshift/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/upstream/olm/metering.catalogsourceconfig.yaml
Labels: approved

#1159 Update dev docs for go mod changes
  Documentation/dev/developer-guide.md
Labels: approved, lgtm

#1160 Dockerfile: Update metering-ansible-operator image to work with rhel 8.1.
  Dockerfile.metering-ansible-operator
Labels: approved

#1158 *: Connect to the thanos-querier API instead of the cluster-wide Prometheus instance.
  Documentation/configuring-reporting-operator.md
  charts/openshift-metering/templates/monitoring/monitoring-rbac.yaml
  cmd/reporting-operator/start.go
  hack/run-reporting-operator-local.sh
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
Labels: approved, lgtm

#1161 Makefile: Build the deploy-metering binary with the GO_BUILD_ARG options.
  Makefile
Labels: approved, lgtm

#1162 OWNERS: Add the Bugzilla component information.
  OWNERS
Labels: approved, lgtm

#1140 *: Add support for running upgrade tests in the end-to-end suite.
  Makefile
  hack/create-upgrade-configmap.sh
  hack/e2e.sh
  hack/gather-test-install-artifacts.sh
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/deployframework/local.go
  test/e2e/main_test.go
  test/e2e/report_dynamic_input_data_test.go
  test/e2e/report_static_input_data_test.go
  test/reportingframework/reportquery.go
  test/testhelpers/assert.go
  test/testhelpers/helpers.go
Labels: approved, lgtm

#1163 pkg/deploy: Fix the hive-metastore PVC label selector.
  pkg/deploy/uninstall.go
Labels: approved, lgtm

#1106 proxy enablement
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
Labels: approved, lgtm, size/XS

#1165 Makefile: Only run the manual metering e2e tests by default.
  Makefile
Labels: approved, lgtm

#1164 *: Respect cluster-wide Proxy configuration.
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/reporting-operator/reporting-operator-config.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-trusted-ca-bundle-configmap.yaml
  charts/openshift-metering/values.yaml
  cmd/reporting-operator/start.go
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
  pkg/aws/client.go
  pkg/operator/datasources.go
  pkg/operator/operator.go
  test/deployframework/helpers.go
Labels: approved, lgtm

#1166 pkg/apis: Update the prometheus-connector configuration in the metering client.
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
Labels: approved, lgtm

#1167 Add annotation requirement to csv
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1169 Updating reference to latest kubeprometheus github
  Documentation/install-metering.md
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test

#1168 Removing testing ocp images section
  Documentation/dev/developer-guide.md
Labels: approved, bugzilla/valid-bug, lgtm

#1171 charts,manifests: Fix the operators capability console annotation.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1173 Makefile: Disable the upgrade-aws prow test.
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm

#1176 Providing reference to hive metastore objects from documentation
  Documentation/configuring-hive-metastore.md
Labels: approved, bugzilla/valid-bug, lgtm

#1178 Providing reference to kube state metrics page
  Documentation/install-metering.md
Labels: approved, bugzilla/valid-bug, lgtm

#1175 Minor grammatical fixture
  Documentation/tuning.md
Labels: approved, bugzilla/valid-bug, lgtm

#1197 Bug 1829035: Remove all instances of the k8s_event module.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1199 Bug 1829035: Stop loading the presto-prometheus connector.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/templates/presto/presto-catalog-config-secret.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-prometheus-auth.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringconfig.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringconfig.crd.yaml
  test/e2e/main_test.go
  test/e2e/presto_prometheus_connector_up_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1202 Makefile: Stop passing EXTRA_TEST_FLAGS to the e2e make target.
  Makefile
Labels: approved
