Repository kube-reporting/metering-operator, pull requests merged in 2020-02, with the labels that each got.

#1097 Bug 1799054: Add support for suggested namespace and cluster monitoring annotations in OLM.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1072 Support querying unmanaged, existing Presto table metadata.
  charts/metering-ansible-operator/templates/crds/prestotable.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/prestotable.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/prestotable.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/prestotable.crd.yaml
  pkg/operator/prestotables.go
  pkg/operator/reporting/db.go
  pkg/presto/util.go
Labels: approved, lgtm, size/L

#1094 Bug 1790601: Fix description of runImmediately
  Documentation/reports.md
  pkg/operator/reports.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1099 Bug 1795267: Support updating existing clusterrole/clusterrolebindings when install Metering.
  pkg/deploy/install.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1101 Bug 1802638: Allow support for creating an S3 bucket on an IPV6 cluster.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#1102 Dockerfile: Require the setuptools python package to be less than the 45.2.0 version.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
Labels: approved, size/XS

#1092 Bug 1797801: Update the Hive and reporting-operator charts to work with single-stack ipv4 and ipv6.
  charts/openshift-metering/templates/hive/hive-configmap.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1105 Bug 1799054: Add quotations around the cluster-monitoring CSV annotation.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1093 Errant "the" removed
  Documentation/reports.md
Labels: approved, lgtm, size/XS

#1109 charts,manifests: Add support for upgrading between Metering CSV versions.
  charts/metering-ansible-operator/templates/olm/art.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
  manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#1110 [release-4.4] Bug 1807229: Add quotations around the openshift.io/cluster-monitoring CSV annotation.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
