Repository kube-reporting/metering-operator, pull requests merged in 2020-08, with the labels that each got.

#1345 pkg/operator: Remove redundant else clause for the op.dropPrestoTable method.
  pkg/operator/prestotables.go
Labels: approved, lgtm

#1347 pkg/operator: Fix failing verification check in master by running go fmt.
  pkg/operator/reports.go
Labels: approved

#1349 pkg/operator: Add the value of the missing format specification when firing off Report events.
  pkg/operator/operator.go
Labels: approved, lgtm

#1348 pkg/operator: Use the parent logger from op.syncReport instead of the built-in reporting logger.
  pkg/operator/operator.go
  pkg/operator/reports.go
Labels: approved, lgtm

#1351 pkg/operator: Fix poor rebase when re-organizing of the op.handleExpiredReport method.
  pkg/operator/reports.go
Labels: approved

#1350 pkg/operator: Requeue a Report that has reached its expiration date during the op.runReport method.
  pkg/operator/reports.go
Labels: approved, lgtm

#1346 Renames *_tests to *_test
  test/e2e/ensure_leader_election_event_is_created_test.go
  test/e2e/metering_manual_install_test.go
Labels: approved, lgtm

#1355 test/e2e: Disable the s3 bucket test installation by default.
  test/e2e/main_test.go
Labels: approved, lgtm

#1358 test/e2e: Disable the MySQL Hive metastore e2e test.
  test/e2e/main_test.go
Labels: approved, lgtm

#1362 olm_deploy: Add the metering-ansible-operator bundle format.
  Dockerfile.bundle
  olm_deploy/bundle/manifests/hive.crd.yaml
  olm_deploy/bundle/manifests/meteringconfig.crd.yaml
  olm_deploy/bundle/manifests/meteringoperator.v4.6.0.clusterserviceversion.yaml
  olm_deploy/bundle/manifests/prestotable.crd.yaml
  olm_deploy/bundle/manifests/report.crd.yaml
  olm_deploy/bundle/manifests/reportdatasource.crd.yaml
  olm_deploy/bundle/manifests/reportquery.crd.yaml
  olm_deploy/bundle/manifests/storagelocation.crd.yaml
  olm_deploy/bundle/metadata/annotations.yaml
Labels: approved, lgtm

#1363 Go standard has test filenames ending in test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, lgtm

#1267 [release-4.4] Bug 1849221: Migrate to obtaining the service-serving CA bundle from a ConfigMap.
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml
  charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1311 add sharedStorage option to CI
  test/e2e/main_test.go
  test/e2e/manifests/meteringconfigs/nfs.yaml
  test/e2e/manifests/nfs/persistentvolume.yaml
  test/e2e/manifests/nfs/server.yaml
  test/e2e/manifests/nfs/service.yaml
  test/e2e/manifests/nfs/storageclass.yaml
  test/e2e/metering_manual_install_test.go
Labels: approved, lgtm

#1365 Documentation,charts,manifests: Update the upstream logo.
  Documentation/operator_logo_metering_color.png
  Documentation/operator_logo_metering_color.svg
  Documentation/upstream_metering_logo.svg
  charts/metering-ansible-operator/upstream-values.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1368 test: Upgrade from metering version that contains the 4.5 many-to-many fix.
  test/deployframework/helpers.go
  test/e2e/metering_upgrade_test.go
Labels: approved, lgtm

#1372 hack: Gather the metering-related CRDs during test execution.
  hack/gather-test-install-artifacts.sh
Labels: approved, lgtm

#1370 hack: Fix array variable expansion in e2e.sh.
  hack/e2e.sh
Labels: approved, lgtm

#1356 Operator refactor - validation and import cleanup
  pkg/operator/aws_usage_hive.go
  pkg/operator/datasources.go
  pkg/operator/health.go
  pkg/operator/hivetables.go
  pkg/operator/operator.go
  pkg/operator/prestotables.go
  pkg/operator/promsum.go
  pkg/operator/queues.go
  pkg/operator/reportquery.go
  pkg/operator/reports.go
  pkg/operator/storage.go
  pkg/operator/storagelocations.go
  pkg/operator/types.go
  pkg/operator/validation.go
  pkg/operator/validation_test.go
Labels: approved, lgtm

#1366 olm_deploy: Use the ubi8-minimal base image for the registry Dockerfile.
  olm_deploy/Dockerfile.registry
Labels: approved, lgtm

#1361 test: Add comments and perform general cleanup for the various reportingframework method and functions.
  test/e2e/report_static_input_data_test.go
  test/reportingframework/datasource.go
  test/reportingframework/db.go
  test/reportingframework/framework.go
  test/reportingframework/prestotables.go
  test/reportingframework/report.go
  test/reportingframework/service.go
Labels: approved

#1388 Dockerfile: Install the pip3 rpm for the metering-ansible-operator
  Dockerfile.metering-ansible-operator
Labels: approved, bugzilla/valid-bug, lgtm
