Repository kube-reporting/metering-operator, pull requests merged in 2020-03, with the labels that each got.

#1112 Documentation/dev: Update the debugging.md documentation
  Documentation/dev/debugging.md
Labels: approved, lgtm, size/M

#1098 Doc fix
  Documentation/dev/developer-guide.md
Labels: approved, lgtm, size/XS

#1104 charts,manifests,pkg: Support create unmanaged PrestoTables from a ReportDataSource.
  charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/reportdatasource.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.4/reportdatasource.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.4/reportdatasource.crd.yaml
  pkg/apis/metering/v1/report_datasource.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
Labels: approved, lgtm, size/L

#1113 Dockerfile,images: Update the OCP metering-ansible-operator Dockerfile to use the exec-entrypoint sub-command.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  images/metering-ansible-operator/scripts/entrypoint.sh
Labels: approved, lgtm, size/M

#1111 Add support for manually deploying Metering through OLM.
  Gopkg.lock
  cmd/deploy-metering/main.go
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
  test/deployframework/context.go
  test/deployframework/framework.go
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/LICENSE
  vendor/github.com/operator-framework/operator-lifecycle-manager/deploy/ocp/manifests/latest
  vendor/github.com/operator-framework/operator-lifecycle-manager/deploy/upstream/manifests/latest
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/operatorgroup_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/operatorgroup_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.conversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/scheme/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/generated_expansion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/operatorgroup.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1/operators_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/catalogsource.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/generated_expansion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/installplan.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/operators_client.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/client/clientset/versioned/typed/operators/v1alpha1/subscription.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/version/version.go
Labels: approved, lgtm, size/XXL

#1114 Dockerfile: Update the metering-ansible-operator to use the Ansible 2.8 and newer versions.
  Dockerfile.metering-ansible-operator
Labels: approved, lgtm, size/XS

#1116 images: Validate the S3 credentials secret exists before continuing role execution.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
Labels: approved, lgtm, size/M

#1117 hack: Remove unused kube-prometheus-helm-values.yaml file.
  hack/kube-prometheus-helm-values.yaml
Labels: approved, lgtm, size/S

#1120 Fix doc for up-to-date settings
  Documentation/install-metering.md
Labels: approved, lgtm, ok-to-test, size/XS

#1124 Revert "Merge pull request #1114 from timflannagan1/remove-ansible-2.8-pip-install".
  Dockerfile.metering-ansible-operator
Labels: approved, lgtm, size/XS

#1118 Remove and stop generating the ocp-testing deploy manifests.
  Documentation/dev/developer-guide.md
  Documentation/dev/testing-ocp-images.md
  Documentation/dev/testing-olm-install.md
  Documentation/dev/testing-olm-ocp-install.md
  charts/metering-ansible-operator/ocp-testing-values.yaml
  hack/generate-metering-manifests.sh
  manifests/deploy/ocp-testing/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-clusterrolebinding.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-role.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-rolebinding.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-service-account.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/meteringconfig.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/report.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/reportquery.crd.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/storagelocation.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/hive.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/image-references
  manifests/deploy/ocp-testing/olm/bundle/4.5/meteringconfig.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/prestotable.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/report.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/reportdatasource.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/reportquery.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.5/storagelocation.crd.yaml
  manifests/deploy/ocp-testing/olm/bundle/metering.package.yaml
  manifests/deploy/ocp-testing/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/ocp-testing/olm/metering.operatorgroup.yaml
  manifests/deploy/ocp-testing/olm/metering.subscription.yaml
Labels: approved, lgtm, size/XXL

#1123 Merge branch feature-prom-connector.
  charts/metering-ansible-operator/templates/crds/prestotable.crd.yaml
  charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.5/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.5/reportdatasource.crd.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.5/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.5/reportdatasource.crd.yaml
  pkg/apis/metering/v1/report_datasource.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
  pkg/operator/datasources.go
  pkg/operator/prestotables.go
  pkg/operator/reporting/db.go
  pkg/presto/util.go
Labels: approved, lgtm, size/L

#1085 test/e2e: Update the prometheus connector e2e test.
  test/e2e/presto_prometheus_connector_up_test.go
Labels: approved, lgtm, size/M

#1125 nit: fix output to fit for current output in doc
  Documentation/install-metering.md
Labels: needs-ok-to-test

#1119 Dockerfile.src: Add the latest tag to the openshift cli image.
  Dockerfile.src
Labels: approved, lgtm, size/XS

#1126 hack,Makefile: Support overriding the script package path in the update-codegen script.
  Makefile
  hack/update-codegen.sh
Labels: approved, lgtm

#1127 Correcting the link for reporting operator logs
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, needs-ok-to-test

#1130 Correcting a link in documentation
  Documentation/writing-custom-queries.md
Labels: approved, lgtm, needs-ok-to-test

#1131 test/reportingframework: Remove unused constant variable and add the key field to a composite literal.
  test/reportingframework/report.go
  test/reportingframework/service.go
Labels: approved, lgtm

#1129 README: Update the project's status and conform with the structuring of the other operator-framework projects.
  README.md
Labels: approved, lgtm

#1134 Provide references to external documentations of presto-cli & beeline
  Documentation/dev/debugging.md
Labels: approved, lgtm, ok-to-test

#1136 Updating reference to yaml file in manifests folder
  Documentation/dev/developer-guide.md
Labels: approved, lgtm, ok-to-test

#1137 Providing a link to shell script file location
  Documentation/dev/mirroring-ocp-images.md
Labels: approved, lgtm, ok-to-test

#1138 Providing reference to external rfc3339 documentation
  Documentation/reports.md
Labels: needs-ok-to-test

#1135 Adds revision hash that was missing for OLM package
  Gopkg.lock
Labels: approved, lgtm

#1139 Adding reference to hive documentation of partitioned tables
  Documentation/hivetables.md
Labels: approved, lgtm, ok-to-test, skip-all

#1141 CatalogSourceConfig should just be CatalogSource
  manifests/deploy/openshift/olm/metering.catalogsource.yaml
  manifests/deploy/upstream/olm/metering.catalogsource.yaml
Labels: approved, lgtm, ok-to-test, skip-all

#1142 Gopkg.*,vendor: Bump the openshift client-go and it's dependencies to the release-4.2 branch.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#1144 charts,manifests: Stop generating the telemeter manifest list.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/telemeter/list.yaml
Labels: approved, lgtm

#1147 Providing reference to kubectl setup documentation
  Documentation/install-metering.md
Labels: approved, lgtm, ok-to-test

#1148 Correction in index.md for s3 storage section
  Documentation/index.md
Labels: approved, lgtm, ok-to-test

#1145 charts,images,manifests: Add support for auto-detecting when a cluster-wide Proxy has been configured.
  charts/metering-ansible-operator/values.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1143 fix version and CatalogSource has requirement spec.sourceType
  charts/metering-ansible-operator/templates/olm/catalogsource.yaml
  charts/metering-ansible-operator/templates/olm/catalogsourceconfig.yaml
  charts/metering-ansible-operator/templates/olm/operatorgroup.yaml
  charts/metering-ansible-operator/templates/olm/subscription.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  hack/create-metering-manifests.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  manifests/deploy/openshift/olm/metering.catalogsource.yaml
  manifests/deploy/upstream/olm/metering.catalogsource.yaml
Labels: approved, lgtm, ok-to-test

#1151 manifests/deploy: Remove the telemeter manifest set.
  manifests/deploy/openshift/telemeter/list.yaml
Labels: approved

#1146 Makefile: Re-generate the metering manifests during the verify check.
  Makefile
Labels: approved, lgtm

#1153 hack: Capture the deployment and statefulset description before tearing down a test installation.
  hack/run-test-cleanup.sh
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1154 Correcting prometheus link from index.md
  Documentation/index.md
Labels: needs-ok-to-test

#1155 Revert "fix version and CatalogSource has requirement spec.sourceType"
  charts/metering-ansible-operator/templates/olm/catalogsource.yaml
  charts/metering-ansible-operator/templates/olm/catalogsourceconfig.yaml
  charts/metering-ansible-operator/templates/olm/operatorgroup.yaml
  charts/metering-ansible-operator/templates/olm/subscription.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  hack/create-metering-manifests.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  manifests/deploy/openshift/olm/metering.catalogsource.yaml
  manifests/deploy/upstream/olm/metering.catalogsource.yaml
Labels: approved, lgtm
