Repository kube-reporting/metering-operator, pull requests merged in 2020-01, with the labels that each got.

#1068 Rectifying a typo in documentation
  Documentation/api.md
Labels: approved, lgtm, ok-to-test, size/XS

#1043 Add logging of resource installs to k8s_event_module
  images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
Labels: size/L

#1071 Goodbye Oxford comma
  README.md
Labels: approved, lgtm, size/XS

#1073 Documentation: Fix broken link in reportdatasources.md.
  Documentation/reportdatasources.md
Labels: approved, lgtm, size/XS

#1069 Bug 1781499: Fix the invalid tag used in the release-4.2 CSV's container image field.
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.2/meteringoperator.v4.2.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#1070 pkg/operator: Remove unused code and catch potential errors as needed.
  pkg/operator/datasources.go
  pkg/operator/hivetables.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/S

#1076 Improve S3 bucket usage docs
  Documentation/configuring-storage.md
Labels: approved, lgtm, size/S

#1079 Add support for auto-detecting single-stack IPV4/IPV6 Openshift clusters.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  charts/metering-ansible-operator/values.yaml
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#1080 images: Remove the task name for ending the role during an error.
  images/metering-ansible-operator/roles/meteringconfig/tasks/update_meteringconfig_status.yml
Labels: approved, lgtm, size/XS

#1082 Bug 1795267: Allow the metering-operator to get the network openshift config object.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/telemeter/list.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-clusterrole.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1081 Bug 1795241: Add hostAliases with presto -> ipv6 loopback
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1083 Dockerfile.reporting-operator: Bump the Golang compiler version to 1.13.
  Dockerfile.reporting-operator
  Dockerfile.reporting-operator.okd
  Dockerfile.reporting-operator.rhel
Labels: approved, lgtm, size/XS

#1084 Dockerfile.src: Bump the Go compiler to the 1.13 version.
  Dockerfile.src
Labels: approved, lgtm, size/XS

#1087 Revert "Dockerfile.src: Bump the Go compiler to the 1.13 version."
  Dockerfile.src
Labels: approved, size/XS

#1086 Makefile: Remove the test2json dependency and unused PHONY targets.
  Dockerfile.src
  Gopkg.lock
  Gopkg.toml
  Makefile
  gotools/test2json/internal/test2json/test2json.go
  gotools/test2json/main.go
Labels: approved, lgtm, size/XL

#1089 Dockerfile.src: Remove the unused gotools directory and bump the Go compiler version.
  Dockerfile.src
Labels: approved, size/XS

#1077 Bug 1793543: Allow support for using S3 buckets in an IPV6 cluster.
  charts/openshift-metering/templates/hadoop/_hadoop_config_helpers.tpl
  charts/openshift-metering/templates/presto/_presto_helpers.tpl
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  pkg/operator/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#1088 Bug 1787745: Remove the RSA's md5 algorithm from the Ansible openssl modules.
  images/metering-ansible-operator/roles/meteringconfig/module_utils/crypto.py
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
