Repository kube-reporting/metering-operator, pull requests merged in 2020-12, with the labels that each got.

#1428 Migrate to using the v1.x ansible-operator
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel8
  bundle/manifests/meteringoperator.v4.7.0.clusterserviceversion.yaml
  charts/metering-ansible-operator/templates/_helpers.tpl
  charts/metering-ansible-operator/values.yaml
  images/metering-ansible-operator/watches.yaml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/upstream/olm/bundle/4.7/meteringoperator.v4.7.0.clusterserviceversion.yaml
  test/e2e/ensure_leader_election_configmap_is_created_test.go
Labels: approved, lgtm

#1453 cmd: Add a CLI helpers package
  cmd/deploy-metering/main.go
  cmd/helpers/helpers.go
  cmd/reporting-operator/start.go
Labels: approved, lgtm

#1458 Dockerfile: Avoid using docker.io base images
  Dockerfile.reporting-operator
  Dockerfile.src
Labels: approved

#1446 [release-4.6] Bug 1897379: Fix the HiveTable status.partitions schema definition
  charts/metering-ansible-operator/templates/crds/hive.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/hive.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/hive.crd.yaml
  olm_deploy/bundle/manifests/hive.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1456 [release-4.5] Dockerfile: Avoid using the latest tag for the Helm image in CI
  Dockerfile.metering-ansible-operator
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1462 Enhance docu for Basic Auth with htpasswd.data
  Documentation/configuring-reporting-operator.md
Labels: approved, bugzilla/valid-bug, lgtm
