Repository kube-reporting/metering-operator, pull requests merged in 2020-06, with the labels that each got.

#1226 *: Bump the repository to use the 4.6 images and re-generate YAML manifests.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  Documentation/install-metering.md
  Documentation/manual-olm-install.md
  Documentation/olm-install.md
  Makefile
  charts/metering-ansible-operator/templates/olm/art.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  charts/openshift-metering/values.yaml
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.6/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/image-references
  manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.6/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
  manifests/deploy/openshift/olm/bundle/metering.package.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/upstream/olm/bundle/4.6/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/image-references
  manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.6/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/reportquery.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/storagelocation.crd.yaml
  manifests/deploy/upstream/olm/bundle/metering.package.yaml
  manifests/deploy/upstream/olm/metering.subscription.yaml
Labels: approved, lgtm

#1229 Bug 1842978: Migrate to obtaining the service-serving CA bundle from a ConfigMap.
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml
  charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1228 charts: Reference the correct serviceaccount to allow Prometheus to scrape Metering endpoints properly.
  charts/openshift-metering/templates/monitoring/monitoring-rbac.yaml
Labels: approved, lgtm

#1224 images: Finalize the meteringconfig_spec_overrides dictionary before running any top-level tasks.
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, lgtm

#1233 Minor typo fix
  Documentation/dev/ocp-images.md
Labels: needs-ok-to-test

#1234 Correcting case
  Documentation/dev/builds.md
Labels: needs-ok-to-test

#1232 Minor typo fix
  Documentation/reportdatasources.md
Labels: needs-ok-to-test

#1230 [release-4.5] Bug 1842977: Migrate to obtaining the service-serving CA bundle from a ConfigMap
  charts/openshift-metering/templates/hadoop/hadoop-scripts.yaml
  charts/openshift-metering/templates/hadoop/hdfs-datanode-statefulset.yaml
  charts/openshift-metering/templates/hadoop/hdfs-namenode-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-metastore-statefulset.yaml
  charts/openshift-metering/templates/hive/hive-scripts-configmap.yaml
  charts/openshift-metering/templates/hive/hive-server-statefulset.yaml
  charts/openshift-metering/templates/metering/metering-service-ca-crt.yaml
  charts/openshift-metering/templates/monitoring/reporting-operator-service-monitor.yaml
  charts/openshift-metering/templates/presto/presto-common-config.yaml
  charts/openshift-metering/templates/presto/presto-coordinator-statefulset.yaml
  charts/openshift-metering/templates/presto/presto-worker-statefulset.yaml
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#1231 [release-4.5] Bug 1843178: Reference the correct serviceaccount to allow Prometheus to scrape Metering endpoints properly.
  charts/openshift-metering/templates/monitoring/monitoring-rbac.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#1236 pkg/deploy: Delete all clusterroles/clusterrolebindings matching the 'app=reporting-operator' selector.
  pkg/deploy/uninstall.go
Labels: approved, lgtm

#1239 Update tuning.md
  Documentation/tuning.md
Labels: needs-ok-to-test

#1241 Bug 1838652: Ensure the MeteringConfig CRD exists and has a populated Status field.
  go.sum
  pkg/deploy/install.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1214 Add Hive Secret for MySql
  Documentation/configuring-hive-metastore.md
  charts/openshift-metering/values.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_metastore.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  pkg/apis/metering/v1/metering_config.go
Labels: lgtm

#1242 CHANGELOG: Add initial 4.6 release notes tracking.
  CHANGELOG.md
Labels: approved

#1240 images: Ensure the randomly generated cookie seed string matches 32 characters in length.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
Labels: approved, lgtm

#1243 charts,manifests: Bump the lower bound upgrade range from 4.2 to 4.3 in the Metering CSV manifests.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1246 Documentation: Remove note about not recommending NFS for shared storage.
  Documentation/configuring-storage.md
Labels: approved, lgtm

#1244 test/e2e: Replace the MeteringConfig Golang objects with decoded YAML manifests.
  test/e2e/main_test.go
  test/e2e/testdata/meteringconfigs/missing-storage.yaml
  test/e2e/testdata/meteringconfigs/prometheus-metrics-importer-disabled.yaml
  test/e2e/testdata/meteringconfigs/prometheus-metrics-importer-enabled.yaml
Labels: approved, lgtm

#1250 hack,test: Prepend the namespace prefix to the testing namespace label we apply for multi-tenancy.
  hack/e2e.sh
  test/deployframework/framework.go
Labels: approved, lgtm

#1249 cmd/deploy-metering: Bump the default OLM channel from 4.2 to 4.4.
  cmd/deploy-metering/main.go
Labels: approved, lgtm

#1248 test/e2e: Re-organize the top-level test functions into their own files.
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
  test/e2e/metering_upgrade_tests.go
Labels: approved, lgtm

#1254 test/e2e: Re-enabled skipped e2e tests.
  test/e2e/main_test.go
Labels: approved, lgtm

#1255 Bug 1847151: Fix the olm.skipRange CSV annotation being rendered incorrectly.
  charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1256 [release-4.5] Bug 1847154: Fix the olm.skipRange CSV annotation being rendered incorrectly.
  charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.5/meteringoperator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#1245 Documentation,images: Generalize and update the configuring_hive_metastore task file.
  CHANGELOG.md
  Documentation/configuring-hive-metastore.md
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_metastore.yml
Labels: approved, lgtm

#1257 Bug 1844240: Fix many-to-many occasional e2e errors by adding `label_replace()` to handle missing `volumename`
  charts/openshift-metering/values.yaml
  pkg/operator/prestostore/query.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug

#1261 Revert "Bug 1844240: Fix many-to-many occasional e2e errors by adding `label_replace()` to handle missing `volumename`"
  charts/openshift-metering/values.yaml
  pkg/operator/prestostore/query.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-low

#1260 First pass jq faq without hack/faq.repo copy
  Dockerfile.src
Labels: approved

#1263 Get faq via static Linux binary
  Dockerfile.src
Labels: approved

#1262 Bug 1844240: Fix many-to-many occasional e2e errors by adding `label_replace()` to handle missing `volumename`
  charts/openshift-metering/values.yaml
  pkg/operator/prestostore/query.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1266 hack: Add the '-mod=vendor' go test option.
  hack/e2e.sh
Labels: approved, lgtm

#1259 charts: Remove the unused metering-ci helm charts.
  charts/metering-ci/Chart.yaml
  charts/metering-ci/templates/metering.yaml
  charts/metering-ci/values.yaml
Labels: approved, lgtm

#1237 Documentation: Update stale documentation and add references to watching k8s events.
  Documentation/configuring-storage.md
  Documentation/dev/debugging.md
  Documentation/hivetables.md
  Documentation/manual-install.md
  Documentation/tuning.md
Labels: approved

#1238 Documentation/dev: Add documentation for the deploy-metering CLI utility.
  Documentation/dev/deploy-metering.md
Labels: approved

#1253 Bump the metering-related CRDs to use apiextensions.k8s.io/v1.
  CHANGELOG.md
  Makefile
  charts/metering-ansible-operator/templates/crds/hive.crd.yaml
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  charts/metering-ansible-operator/templates/crds/prestotable.crd.yaml
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  charts/metering-ansible-operator/templates/crds/reportdatasource.crd.yaml
  charts/metering-ansible-operator/templates/crds/reportquery.crd.yaml
  charts/metering-ansible-operator/templates/crds/storagelocation.crd.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  cmd/deploy-metering/main.go
  hack/e2e.sh
  manifests/deploy/openshift/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/reportquery.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.6/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/storagelocation.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/hive.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/prestotable.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/report.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/reportdatasource.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/reportquery.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/storagelocation.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.6/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/reportquery.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/storagelocation.crd.yaml
  pkg/apis/metering/v1/hive_table.go
  pkg/apis/metering/v1/presto_table.go
  pkg/deploy/deploy.go
  pkg/deploy/helpers.go
  test/deployframework/context.go
  test/deployframework/framework.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm

#1269 Try group_right as less prone to many-to-many
  charts/openshift-metering/values.yaml
Labels: approved, lgtm

#1271 pkg/deploy: Update the label selector used to delete the metering clusterroles/clusterrolebindings.
  pkg/deploy/uninstall.go
Labels: approved

#1272 Dockerfile.src: Get the faq dependency via a static Linux binary.
  Dockerfile.src
Labels: approved

#1268 images: Fix conditional when checking if the cluster-wide proxy has been configured.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
Labels: approved, lgtm

#1270 pkg/deploy: Cleanup conditional structure in the top-level deploy methods.
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
Labels: approved, lgtm

#1273 cmd,pkg/deploy: Support passing a list of configurable OLM flagsets/environment variables.
  cmd/deploy-metering/main.go
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
Labels: approved, lgtm

#1275 pkg/deploy: Update the uninstallMeteringPVCs method to only list the hdfs PVCs.
  pkg/deploy/deploy.go
  pkg/deploy/uninstall.go
Labels: approved

#1277 hack: Update the must-gather test artifacts script to use 'oc adm inspect'.
  hack/gather-test-install-artifacts.sh
Labels: approved, lgtm

#1278 addition of styling in Documentation/configuring-reporting-operator.md
  Documentation/configuring-reporting-operator.md
Labels: needs-ok-to-test

#1279 hack,olm_deploy: Add an additional set of manifests used to build a local bundle registry.
  hack/push-olm-manifests.sh
  olm_deploy/Dockerfile.registry
  olm_deploy/manifests/deployment.yaml
  olm_deploy/manifests/service.yaml
  olm_deploy/scripts/init-bundle-registry.sh
Labels: approved, lgtm

#1281 olm_deploy: Provide the Openshift OLM bundle as the default value for the MANIFEST_BUNDLE build argument.
  olm_deploy/Dockerfile.registry
Labels: approved

#1252 Dockerfile,Makefile: Rename the metering-ansible-operator origin Dockerfile to have a .okd suffix.
  Dockerfile.metering-ansible-operator.okd
  Makefile
Labels: approved, lgtm

#1276 test/e2e: Add a wrapper function around the top-level TestMain function.
  test/e2e/main_test.go
Labels: approved, lgtm

#1274 hack,pkg,test: Update the e2e suite to support deploying Metering using OLM.
  hack/e2e.sh
  hack/lib/tests.sh
  pkg/deploy/uninstall.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
  test/e2e/metering_upgrade_tests.go
  test/reportingframework/datasource.go
  test/reportingframework/prestotables.go
  test/reportingframework/report.go
  test/reportingframework/reportquery.go
  test/reportingframework/service.go
Labels: approved, lgtm

#1287 [release-4.3] Dockerfile.src: Get the faq dependency via a static Linux binary.
  Dockerfile.src
Labels: approved

#1284 chart,manifests: Fix issue where configuring resource requirements for Metering gets purged.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
Labels: approved, lgtm

#1283 Documentation/dev: Update the e2e documentation in the developer-guide.md
  Documentation/dev/developer-guide.md
Labels: approved, lgtm

#1285 test/deployframework: Delete the ClusterRole and ClusterRoleBinding resources by default in the testing suite.
  test/deployframework/framework.go
Labels: approved, lgtm

#1280 Changes needed to accomodate the move of our forked Presto to v328
  charts/openshift-metering/templates/presto/presto-coordinator-config.yaml
  charts/openshift-metering/templates/presto/presto-worker-config.yaml
Labels: approved, lgtm

#1286 charts,manifests: Replace the 'hour' property with the 'second' property for the hourly reports schema definition.
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml
Labels: approved, lgtm
