Repository kube-reporting/metering-operator, pull requests merged in 2020-07, with the labels that each got.

#1288 test: Add support for running multiple post-install Metering tests.
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/registry.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
  test/testhelpers/helpers.go
Labels: approved, lgtm

#1290 test: Add a post-install test for checking if the service-serving CA bundle has been properly mounted.
  go.sum
  test/e2e/main_test.go
  test/e2e/presto_prometheus_connector_up_test.go
  test/e2e/service_serving_ca_bundle_exists_test.go
  test/reportingframework/framework.go
  test/testhelpers/helpers.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: approved, lgtm

#1294 Remove an is
  Documentation/reportqueries.md
Labels: approved

#1295 Doc fix report related docs
  Documentation/reportdatasources.md
  Documentation/reportqueries.md
Labels: approved, lgtm

#1225 [release-4.4] Bug 1847111: Add support for upgrading between Metering CSV versions.
  charts/metering-ansible-operator/templates/olm/art.yaml
  charts/metering-ansible-operator/templates/olm/clusterserviceversion.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/ocp-testing/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
  manifests/deploy/upstream/olm/bundle/4.4/meteringoperator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1297 test/e2e: Add support for running any pre-installation tests.
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
Labels: approved, lgtm

#1296 test/e2e: Add support for running post-install tests against a Metering installation using s3.
  Dockerfile.metering-ansible-operator
  test/e2e/delete_s3_bucket_test.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
  test/e2e/testdata/meteringconfigs/s3.yaml
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/batch.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/bucket_region.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/buffered_read_seeker.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/default_read_seeker_write_to.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/default_read_seeker_write_to_windows.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/default_writer_read_from.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/default_writer_read_from_windows.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/doc.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/read_seeker_write_to.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/writer_read_from.go
  vendor/modules.txt
Labels: approved, lgtm

#1306 hack,test/e2e: Add support for skipping any top-level MeteringConfig manual installations.
  hack/e2e.sh
  test/e2e/main_test.go
Labels: approved, lgtm

#1308 test/e2e: Fix the conditional for skipping any Metering installation tests
  test/e2e/main_test.go
Labels: approved

#1305 test/e2e: Wait for the s3 bucket to be deleted.
  test/e2e/delete_s3_bucket_test.go
Labels: approved, lgtm

#1307 hack,test: Re-enable upgrade testing.
  hack/e2e.sh
  test/deployframework/context.go
  test/deployframework/helpers.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
  test/e2e/metering_upgrade_tests.go
  test/testhelpers/helpers.go
Labels: approved, lgtm

#1310 charts,manifests: Fix missing schema definitions for map[string]string API fields.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringconfig.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringconfig.crd.yaml
Labels: approved, lgtm

#1300 hack: Bump the default channel in the get-metering-package-images script.
  hack/get-metering-package-images.sh
Labels: approved, lgtm

#1309 Add an e2e test for validating a custom node selector configuration.
  hack/e2e.sh
  test/e2e/custom_node_selector_tests.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_tests.go
  test/e2e/testdata/meteringconfigs/node-selector-prometheus-importer-disabled.yaml
Labels: approved, lgtm

#1312 Add a Dockerfile for building the deploy-metering CLI utility.
  Dockerfile.deploy-metering
Labels: approved

#1317 hack: Gather the InstallPlan resources in the test metering namespace.
  hack/gather-test-install-artifacts.sh
Labels: approved

#1315 hack,test/e2e: Default to the 4.6 operator registry image CI imagestream.
  hack/e2e.sh
  test/e2e/main_test.go
Labels: approved

#1322 charts,manifests: Lower the minKubeVersion to 1.17.0 to unblock CI.
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1313 test/e2e: Move the MeteringConfig YAML manifests to its own directory.
  test/e2e/main_test.go
  test/e2e/manifests/meteringconfigs/missing-storage.yaml
  test/e2e/manifests/meteringconfigs/node-selector-prometheus-importer-disabled.yaml
  test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-disabled.yaml
  test/e2e/manifests/meteringconfigs/prometheus-metrics-importer-enabled.yaml
  test/e2e/manifests/meteringconfigs/s3.yaml
Labels: approved

#1314 test/e2e: Add an e2e test for configuring a MySQL instance for Hive metastore.
  test/e2e/main_test.go
  test/e2e/manifests/meteringconfigs/mysql.yaml
  test/e2e/metering_manual_install_tests.go
Labels: approved, lgtm

#1325 update to non-deprecated informer factory method
  pkg/operator/operator.go
Labels: approved, lgtm

#1328 hack,olm_deploy: Add a script and manifests that enables horizontal machine autoscaling.
  hack/e2e.sh
  hack/enable-machine-autoscaling.sh
  olm_deploy/manifests/machines/clusterautoscaler.yaml
  olm_deploy/manifests/machines/machineautoscaler.yaml
Labels: approved, lgtm

#1324 Add Dockerfile.metering-ansible-operator.rhel8
  Dockerfile.metering-ansible-operator.rhel8
Labels: approved, lgtm, ok-to-test

#1321 add link to helm cli
  Documentation/dev/developer-guide.md
Labels: approved, lgtm

#1331 remove duplicate import and redundant alias for hive
  pkg/operator/operator.go
Labels: approved, lgtm

#1327 minor wording fixes
  Documentation/manual-install.md
Labels: approved, lgtm

#1334 test/e2e: Disable the node selector e2e test by default.
  test/e2e/main_test.go
Labels: approved, lgtm

#1291 charts/openshift-metering: Remove unneeded check for the hadoop-gcs-credentials helm charts.
  charts/openshift-metering/templates/hadoop/hadoop-gcs-credentials.yaml
Labels: approved, lgtm

#1319 Documentation,charts,manifests: Update the downstream logo.
  Documentation/downstream_metering_logo.png
  Documentation/downstream_metering_logo.svg
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1335 charts,manifests: Add the zap-level argument to the ansible-operator container.
  charts/metering-ansible-operator/templates/_helpers.tpl
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1293 charts,manifests: Update the Report CRD to add a schema for 'spec.overwriteExistingData'.
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml
Labels: approved, lgtm

#1336 test/e2e: Add a post-install test that verifies that the metering-ansible-operator is exposing metrics properly.
  test/e2e/main_test.go
  test/e2e/metering_ansible_operator_metrics_test.go
Labels: approved, lgtm

#1332 CHANGELOG,Documentation: Follow-up changes to the removal of the Ansible sidecar container.
  CHANGELOG.md
  Documentation/dev/debugging.md
  Documentation/install-metering.md
Labels: approved, lgtm

#1337 Documentation/dev: Add documentation for copying host binaries to a metering container to help debugging.
  Documentation/dev/debugging.md
Labels: approved, lgtm

#1339 charts,manifests: Update the upstream and downstream CSV descriptions.
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1341 pkg/operator: Add the event recorder field to the Report structure.
  pkg/operator/operator.go
Labels: approved, lgtm

#1329 add unit testing for report util methods.
  pkg/apis/metering/v1/util/report_util.go
  pkg/apis/metering/v1/util/report_util_test.go
  pkg/operator/reports.go
Labels: approved, lgtm

#1343 pkg/operator: Update the scheme used for the event record to include the metering v1 scheme.
  pkg/operator/operator.go
  test/e2e/ensure_leader_election_event_is_created.go
  test/e2e/main_test.go
Labels: approved, lgtm

#1333 document noobaa installation with metering
  Documentation/configuring-storage.md
Labels: approved, lgtm, ok-to-test

#1344 pkg/operator: Improve the debugging experience for invalid Prometheus configurations.
  pkg/operator/datasources.go
  pkg/operator/operator.go
  test/e2e/ensure_no_failed_prometheus_events_test.go
  test/e2e/main_test.go
Labels: approved, lgtm

#1318 charts,manifests: Bump the minimum kubernetes server version to 1.18.3
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  manifests/deploy/openshift/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1323 Allow using podman by passing in runtime var for systems without docker installed.
  Makefile
Labels: approved, lgtm

#1298 Additions for Report expiration
  charts/metering-ansible-operator/templates/crds/report.crd.yaml
  manifests/deploy/openshift/metering-ansible-operator/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.6/report.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.6/report.crd.yaml
  pkg/apis/metering/v1/report.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
  pkg/operator/http_test.go
  pkg/operator/operator.go
  pkg/operator/reporting/templates_test.go
  pkg/operator/reporting/validate_test.go
  pkg/operator/reports.go
  pkg/operator/reports_test.go
  test/testhelpers/helpers.go
Labels: approved, lgtm
