Repository kube-reporting/metering-operator, pull requests merged in 2020-05, with the labels that each got.

#1200 Bug 1829836: Fix performance issues when deploying Metering on Ansible 2.9.6+ versions.
  Dockerfile.metering-ansible-operator
  Dockerfile.metering-ansible-operator.rhel
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1204 Dockerfile,images: Fix the metering-ansible-operator rhel Dockerfile.
  Dockerfile.metering-ansible-operator.rhel
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
Labels: approved, bugzilla/valid-bug, lgtm

#1205 Fix typo in PrestoConnectorPrometheusConfigAuth struct.
  pkg/apis/metering/v1/metering_config.go
  pkg/apis/metering/v1/zz_generated.deepcopy.go
Labels: approved, bugzilla/valid-bug, lgtm

#1208 Bug 1829836: Remove the ansible_failed_task variable from all block/rescue instances.
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1207 OWNERS: Add bentito as an approver and alphabetize file.
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#1206 Helm minor version note and rm dep
  Documentation/dev/developer-guide.md
Labels: approved, bugzilla/valid-bug, lgtm

#1196 Fixes refs to Operator Metering architecture doc
  Documentation/metering-architecture.md
Labels: approved, bugzilla/valid-bug, lgtm

#1203 Bug 1829072: Fix all of the k8s_event module instances.
  images/metering-ansible-operator/roles/meteringconfig/library/k8s_event.py
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hdfs.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_hive.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_metering.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_monitoring.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_presto.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile_reporting_operator.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/update_meteringconfig_status.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1210 pkg/deploy: Lower the initial CRD poll time.
  pkg/deploy/deploy.go
Labels: approved, bugzilla/valid-bug, lgtm

#1209 Bug 1829833: Fix performance issues when deploying Metering on Ansible 2.9.6+ versions.
  Dockerfile.metering-ansible-operator
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_networking.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_reporting_operator_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_root_ca.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/configure_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/deploy_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/prune_resources.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/reconcile.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_storage.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_hive_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_presto_tls.yml
  images/metering-ansible-operator/roles/meteringconfig/tasks/validate_reporting_operator_tls.yml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1211 Makefile: Re-enable the e2e-upgrade make target.
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm

#1215 hack,charts,manifests: Update the manual OLM metering manifests.
  charts/metering-ansible-operator/templates/olm/catalogsource.yaml
  charts/metering-ansible-operator/templates/olm/catalogsourceconfig.yaml
  charts/metering-ansible-operator/templates/olm/operatorgroup.yaml
  charts/metering-ansible-operator/templates/olm/subscription.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  hack/create-metering-manifests.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  manifests/deploy/openshift/olm/metering.catalogsource.yaml
  manifests/deploy/openshift/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
  manifests/deploy/upstream/olm/metering.catalogsource.yaml
  manifests/deploy/upstream/olm/metering.catalogsourceconfig.yaml
  manifests/deploy/upstream/olm/metering.subscription.yaml
  pkg/deploy/uninstall.go
Labels: approved, bugzilla/valid-bug, lgtm

#1216 Bug 1831325: Stop returning an error when running the gather testing artifacts script.
  test/deployframework/helpers.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1218 Bug 1837043: Mount the cluster's certificate authority bundle in the auth-proxy sidecar container.
  charts/openshift-metering/templates/reporting-operator/reporting-operator-deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1219 pkg/deploy: Add the empty openshift.io/node-selector annotation to the metering-operator namespace.
  pkg/deploy/install.go
Labels: approved, bugzilla/valid-bug, lgtm

#1223 Correcting case of software names
  Documentation/tuning.md
Labels: needs-ok-to-test

#1222 Bug 1829446: Disable the presto-prometheus by default for OCP installations.
  charts/metering-ansible-operator/templates/crds/meteringconfig.crd.yaml
  images/metering-ansible-operator/roles/meteringconfig/defaults/main.yml
  manifests/deploy/openshift/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.5/meteringconfig.crd.yaml
  manifests/deploy/upstream/metering-ansible-operator/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.5/meteringconfig.crd.yaml
  test/e2e/main_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
