Repository kube-reporting/metering-operator, pull requests merged in 2021-02, with the labels that each got.

#1480 [release-4.6] Dockerfile: Avoid using dockerhub images in the testing root image
  Dockerfile.src
Labels: approved

#1487 *: Bump repository to use the 4.8 image tags and re-generate YAML manifests
  CHANGELOG.md
  Dockerfile.bundle
  Dockerfile.metering-ansible-operator.rhel8
  Dockerfile.reporting-operator.rhel
  Dockerfile.src
  Documentation/dev/developer-guide.md
  Makefile
  bundle/manifests/meteringoperator.v4.8.0.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  charts/metering-ansible-operator/templates/olm/art.yaml
  charts/metering-ansible-operator/upstream-values.yaml
  charts/metering-ansible-operator/values.yaml
  charts/openshift-metering/values.yaml
  cmd/deploy-metering/main.go
  hack/e2e.sh
  hack/generate-metering-manifests.sh
  hack/get-metering-package-images.sh
  manifests/deploy/openshift/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/openshift/olm/bundle/4.8/hive.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.8/image-references
  manifests/deploy/openshift/olm/bundle/4.8/meteringconfig.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.8/meteringoperator.v4.8.0.clusterserviceversion.yaml
  manifests/deploy/openshift/olm/bundle/4.8/prestotable.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.8/report.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.8/reportdatasource.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.8/reportquery.crd.yaml
  manifests/deploy/openshift/olm/bundle/4.8/storagelocation.crd.yaml
  manifests/deploy/openshift/olm/bundle/art.yaml
  manifests/deploy/openshift/olm/bundle/metering.package.yaml
  manifests/deploy/openshift/olm/metering.subscription.yaml
  manifests/deploy/upstream/metering-ansible-operator/metering-operator-deployment.yaml
  manifests/deploy/upstream/olm/bundle/4.8/hive.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.8/image-references
  manifests/deploy/upstream/olm/bundle/4.8/meteringconfig.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.8/meteringoperator.v4.8.0.clusterserviceversion.yaml
  manifests/deploy/upstream/olm/bundle/4.8/prestotable.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.8/report.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.8/reportdatasource.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.8/reportquery.crd.yaml
  manifests/deploy/upstream/olm/bundle/4.8/storagelocation.crd.yaml
  manifests/deploy/upstream/olm/bundle/metering.package.yaml
  manifests/deploy/upstream/olm/metering.subscription.yaml
  test/e2e/main_test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, lgtm

#1488 test/e2e: Require no error when creating the test output directory
  test/e2e/metering_manual_install_test.go
Labels: approved

#1485 test/e2e: Ensure all e2e test namespaces use correct label
  test/e2e/metering_manual_install_test.go
Labels: approved

#1491 pkg/deploy: Export the Deployer fields
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
Labels: approved, lgtm

#1493 test: Remove safeguards in e2e test handlers when expecting errors
  test/deployframework/context.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, lgtm

#1492 test/e2e: Add a top-level test that tests invalid MeteringConfig manifests
  test/e2e/main_test.go
  test/e2e/metering_manual_install_test.go
Labels: approved, lgtm

#1494 cmd,pkg,test: Rename the DeleteCRB -> DeleteCRBs for the Config structure
  cmd/deploy-metering/main.go
  pkg/deploy/deploy.go
  pkg/deploy/uninstall.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
Labels: approved, lgtm

#1432 hack: Minor updates to the various bash scripts
  hack/codegen_output_files.sh
  hack/common.sh
  hack/create-metering-manifests.sh
  hack/e2e.sh
  hack/extract_helm_dep_repos.sh
  hack/gather-test-install-artifacts.sh
  hack/generate-metering-manifests.sh
  hack/install.sh
  hack/mirror-ose-images-into-cluster.sh
  hack/olm-install.sh
  hack/olm-uninstall.sh
  hack/openshift-install.sh
  hack/openshift-uninstall.sh
  hack/push-olm-manifests.sh
  hack/run-metering-operator-local.sh
  hack/run-reporting-operator-local.sh
  hack/uninstall.sh
  hack/unit.sh
  hack/update-codegen.sh
  hack/update-datasource-fixtures.sh
  hack/upstream-install.sh
  hack/upstream-olm-install.sh
  hack/upstream-olm-uninstall.sh
  hack/upstream-uninstall.sh
  hack/verify-codegen.sh
Labels: approved

#1481 test: Handle failed InstallPlans during e2e installations
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
  test/deployframework/helpers.go
  test/deployframework/registry.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, kind/bug, lgtm

#1499 test/e2e: Fix failed InstallPlan handling in test setup code
  test/deployframework/registry.go
  test/e2e/metering_manual_install_test.go
Labels: approved, lgtm

#1500 [release-4.6] Remove operator-courier from the root Dockerfile
  Dockerfile.src
  Makefile
Labels: approved

#1498 hack: Ensure we gather the Pod description artifacts during e2e runs
  hack/gather-test-install-artifacts.sh
Labels: approved, lgtm

#1501 [release-4.6] Dockerfile.src: Use the registry.ci registry
  Dockerfile.src
Labels: approved

#1496 test/e2e: Reduce number of metering e2e tests per-run
  test/e2e/main_test.go
Labels: approved, lgtm

#1502 Documentation: Address markdown violations
  Documentation/api.md
  Documentation/aws-billing-datasource-schema.md
  Documentation/configuring-storage.md
  Documentation/dev/builds.md
  Documentation/dev/developer-guide.md
  Documentation/dev/mirroring-ocp-images.md
  Documentation/dev/noobaa.md
Labels: approved, lgtm

#1504 Dockerfile.src: Use the registry.ci hostname
  Dockerfile.src
Labels: approved, lgtm

#1503 Makefile: Support passing a list of extra container run flags
  Makefile
Labels: approved, lgtm

#1476 Bug 1926984: Avoid requeueing an expired Report
  pkg/operator/reports.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1495 Bug 1927848: Ensure the github.com/gogo/protobuf indirect dependency uses v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/event/core/event.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode_string.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1509 test/e2e: Cleanup install and upgrade test helper functions
  test/deployframework/context.go
  test/e2e/main_test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, lgtm

#1507 [release-4.7] Handle failed InstallPlans in metering test installations
  cmd/deploy-metering/main.go
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
  test/deployframework/helpers.go
  test/deployframework/registry.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, bugzilla/valid-bug, group-lead-approved, lgtm

#1508 [release-4.6] Handle failed InstallPlans in metering test installations
  cmd/deploy-metering/main.go
  pkg/deploy/deploy.go
  pkg/deploy/install.go
  pkg/deploy/uninstall.go
  test/deployframework/context.go
  test/deployframework/framework.go
  test/deployframework/framework_test.go
  test/deployframework/helpers.go
  test/deployframework/registry.go
  test/e2e/main_test.go
  test/e2e/metering_manual_install_test.go
  test/e2e/metering_upgrade_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1511 test/e2e: Disable ClusterAutoscaler scaling down testing nodes
  test/e2e/manifests/machines/clusterautoscaler.yaml
Labels: approved, lgtm

#1514 Documentation: Update the MySQL Hive Metastore configuration docs
  Documentation/configuring-hive-metastore.md
Labels: approved, lgtm
